import Mathlib.Data.Fintype.BigOperators
import Mathlib.Data.Multiset.Basic
import Mathlib.Data.Set.Basic
import Lean.Elab.Tactic.Omega

/-!
# NRRF764 — Conscious cultural morality as a super-network

This module begins with an interactive sensor/selection loop rather than a machine model.  It
then develops potential determination, a shared network, admissible interactions and memory,
translations of networks, and a carrier-free `0`/`∞` quotient.  The constructions are deliberately
relational: no monetary order, social authority, universal machine, or halting oracle is assumed.

The last section records the operational reading used by later interfaces: problems are shared
readings and solutions are interactions.  Thus a solution is not imported as an external rule;
it is an admissible translation inside the network.
-/

namespace NRRF764

open Function
open scoped BigOperators

universe u v w

/-! ## §1 — One continuous interactive loop of sensor and selection -/

/-- A loop has only a sensor and a selection.  No universal machine or halting oracle is part of
the structure. -/
structure Loop (S : Type u) (Obs : Type v) where
  sense : S → Obs
  select : S → Obs → S

namespace Loop

/-- One interaction of sensor and selection. -/
def step (L : Loop S Obs) (s : S) : S := L.select s (L.sense s)

/-- The run generated by repeatedly interacting with the same loop. -/
def run (L : Loop S Obs) (s : S) : ℕ → S
  | 0 => s
  | n + 1 => L.step (run L s n)

@[simp] theorem run_zero (L : Loop S Obs) (s : S) : L.run s 0 = s := rfl

@[simp] theorem run_succ (L : Loop S Obs) (s : S) (n : ℕ) :
    L.run s (n + 1) = L.step (L.run s n) := rfl

/-- A stream is a run when each next state is the loop's own next interaction. -/
def IsRun (L : Loop S Obs) (x : ℕ → S) : Prop :=
  ∀ n, x (n + 1) = L.step (x n)

theorem run_isRun (L : Loop S Obs) (s : S) : L.IsRun (L.run s) := by
  intro n
  rfl

/-- The future beginning at stage `n`. -/
def continuation (x : ℕ → S) (n : ℕ) : ℕ → S :=
  fun k => x (n + k)

/-- A stream is constant when no two of its stages differ. -/
def IsConstant (x : ℕ → S) : Prop :=
  ∀ i j, x i = x j

/-- Halting is read internally as an eventually constant continuation. -/
def Halts (x : ℕ → S) : Prop :=
  ∃ n, IsConstant (continuation x n)

/-- A continuation is again a run of the same sensor/selection loop. -/
theorem continued_run (L : Loop S Obs) {x : ℕ → S} (hx : L.IsRun x) (n : ℕ) :
    L.IsRun (continuation x n) := by
  intro k
  simpa [continuation, Nat.add_assoc] using hx (n + k)

/-- Halting and a constant continuation are the two directions of the same reading. -/
theorem halts_iff_continuation_const (x : ℕ → S) :
    Halts x ↔ ∃ n, IsConstant (continuation x n) := Iff.rfl

/-- The determined prefix of a stream. -/
def observedPrefix (n : ℕ) (x : ℕ → S) : Fin n → S :=
  fun i => x i

/-- Splitting at any stage loses nothing: the prefix and residual future reconstruct the run. -/
def splitEquiv (n : ℕ) : (ℕ → S) ≃ (Fin n → S) × (ℕ → S) where
  toFun x := (observedPrefix n x, continuation x n)
  invFun p k := if h : k < n then p.1 ⟨k, h⟩ else p.2 (k - n)
  left_inv x := by
    funext k
    by_cases h : k < n
    · simp [h, observedPrefix]
    · have hnk : n ≤ k := Nat.le_of_not_gt h
      simp [h, continuation, Nat.add_sub_of_le hnk]
  right_inv p := by
    apply Prod.ext
    · funext i
      simp [observedPrefix, i.isLt]
    · funext k
      have hnk : ¬n + k < n := by omega
      simp [continuation, hnk]

/-- A claimed finite halting test reads only the first `n` states. -/
def CorrectFiniteHaltingTest (n : ℕ) (test : (Fin n → Bool) → Prop) : Prop :=
  ∀ x : ℕ → Bool, Halts x ↔ test (observedPrefix n x)

private def flipBit : ℕ → Bool
  | 0 => false
  | n + 1 => !(flipBit n)

private theorem flipBit_succ_ne (n : ℕ) : flipBit (n + 1) ≠ flipBit n := by
  cases h : flipBit n <;> simp [flipBit, h]

private def delayedAlternation (n : ℕ) (k : ℕ) : Bool :=
  if k < n then false else flipBit k

private theorem delayedAlternation_not_halts (n : ℕ) :
    ¬ Halts (delayedAlternation n) := by
  rintro ⟨m, hm⟩
  have heq := hm n (n + 1)
  have hmn : ¬m + n < n := by omega
  have hmns : ¬m + n + 1 < n := by omega
  have hindex : m + (n + 1) = (m + n) + 1 := by omega
  have hsame : flipBit (m + n) = flipBit ((m + n) + 1) := by
    simpa only [continuation, delayedAlternation, if_neg hmn, if_neg hmns, hindex] using heq
  exact flipBit_succ_ne (m + n) hsame.symm

/-- No finite prefix decides eventual constancy.  This is a stream theorem, not an invocation of
machine undecidability. -/
theorem no_finite_halting_test (n : ℕ) :
    ¬ ∃ test : (Fin n → Bool) → Prop, CorrectFiniteHaltingTest n test := by
  rintro ⟨test, htest⟩
  let flat : ℕ → Bool := fun _ => false
  have hflat : Halts flat := ⟨0, by intro i j; rfl⟩
  have hprefix : observedPrefix n flat = observedPrefix n (delayedAlternation n) := by
    funext i
    simp [observedPrefix, flat, delayedAlternation, i.isLt]
  have haccepted : test (observedPrefix n flat) := (htest flat).mp hflat
  have hdelayed : Halts (delayedAlternation n) :=
    (htest (delayedAlternation n)).mpr (by simpa [hprefix] using haccepted)
  exact delayedAlternation_not_halts n hdelayed

/-- Cantor diagonalization: no state-indexed family lists every binary selection on those states.
This theorem does not assert or assume Turing completeness. -/
theorem no_universal_selection {S : Type u} (e : S → (S → Bool)) :
    ¬ Surjective e := by
  intro he
  let diagonal : S → Bool := fun s => !(e s s)
  obtain ⟨s, hs⟩ := he diagonal
  have hpoint := congrFun hs s
  cases h : e s s <;> simp [diagonal, h] at hpoint

end Loop

/-! ## §2 — Indeterminate strings factor their potential determination -/

set_option linter.checkUnivs false in
/-- At every position, an indeterminate string records the type of choices still open there. -/
structure Ind where
  Position : Type u
  possibility : Position → Type v

namespace Ind

variable {I : Ind}

/-- A determination selects one open possibility at every position. -/
abbrev Det (I : Ind) := ∀ i, I.possibility i

/-- Potential determination is exactly the dependent product of its positional possibilities. -/
def detEquivPi (I : Ind) : I.Det ≃ (∀ i, I.possibility i) := Equiv.refl _

/-- In the finite case, the number of determinations is the product of the local possibilities. -/
theorem card_det (I : Ind) [DecidableEq I.Position] [Fintype I.Position]
    [∀ i, Fintype (I.possibility i)] :
    Fintype.card I.Det = ∏ i, Fintype.card (I.possibility i) := by
  exact Fintype.card_pi

/-- Natural choice determines a nonempty family of open possibilities. -/
noncomputable def chooseDet (I : Ind) [∀ i, Nonempty (I.possibility i)] : I.Det :=
  fun i => Classical.choice (inferInstance : Nonempty (I.possibility i))

theorem det_nonempty (I : Ind) [∀ i, Nonempty (I.possibility i)] : Nonempty I.Det :=
  ⟨I.chooseDet⟩

/-- Agreement is local equality at a position. -/
def agree (a b : I.Det) (i : I.Position) : Prop := a i = b i

/-- Equalization replaces precisely the positions named by `s`. -/
noncomputable def equalize (a b : I.Det) (s : Set I.Position) : I.Det := by
  classical
  exact fun i => if h : i ∈ s then b i else a i

theorem equalize_on (a b : I.Det) (s : Set I.Position) {i : I.Position} (hi : i ∈ s) :
    equalize a b s i = b i := by simp [equalize, hi]

theorem equalize_off (a b : I.Det) (s : Set I.Position) {i : I.Position} (hi : i ∉ s) :
    equalize a b s i = a i := by simp [equalize, hi]

/-- Authorship collapses the open product to the determinations agreeing everywhere with `a`. -/
def authorship (a : I.Det) : Set I.Det :=
  {d | ∀ i, d i = a i}

theorem mem_det_collapse_iff (a d : I.Det) :
    d ∈ authorship a ↔ d = a := by
  constructor
  · intro h
    funext i
    exact h i
  · rintro rfl i
    rfl

/-- Global authorship leaves exactly one determination. -/
theorem det_globalCollapse_unique (a : I.Det) :
    ∃! d : I.Det, d ∈ authorship a := by
  refine ⟨a, ?_, ?_⟩
  · intro i
    rfl
  · intro d hd
    exact (mem_det_collapse_iff a d).mp hd

end Ind

/-! ## §3 — The shared field is not an imposed order -/

set_option linter.checkUnivs false in
/-- A network is a shared interactive field.  `read` is consciousness, `shared` is culture, and
`admits` is an invertible moral reinterpretation preserving that field. -/
structure Network where
  Site : Type u
  Reading : Type v
  read : Site → Reading
  admits : Reading ≃ Reading
  shared : Set Reading
  read_shared : ∀ s, read s ∈ shared
  admits_shared : ∀ r, admits r ∈ shared ↔ r ∈ shared

/-- The unary set of sites whose readings remain shared after admission.  Despite the historical
name, this is not a binary order relation. -/
def ruleOf (N : Network) : Set N.Site :=
  {s | N.admits (N.read s) ∈ N.shared}

/-- Admission excludes no site: the admitted-site predicate is universal. -/
theorem ruleOf_eq_top (N : Network) : ruleOf N = Set.univ := by
  ext s
  constructor
  · intro _
    trivial
  · intro _
    exact (N.admits_shared (N.read s)).mpr (N.read_shared s)

/-- An external authority score is irrelevant to membership in the shared field. -/
theorem authority_does_not_exclude (N : Network) {α : Type w}
    (_authority : N.Site → α) (s : N.Site) : N.read s ∈ N.shared :=
  N.read_shared s

def falseNetwork : Network where
  Site := Unit
  Reading := Bool
  read := fun _ => false
  admits := Equiv.refl Bool
  shared := Set.univ
  read_shared := by simp
  admits_shared := by simp

def trueNetwork : Network where
  Site := Unit
  Reading := Bool
  read := fun _ => true
  admits := Equiv.refl Bool
  shared := Set.univ
  read_shared := by simp
  admits_shared := by simp

/-- The unary admitted-site set does not determine a network's readings.  This theorem's legacy
name refers to `ruleOf`; it does not construct an order relation. -/
theorem networks_not_determined_by_order :
    ruleOf falseNetwork = ruleOf trueNetwork ∧
      falseNetwork.read () ≠ trueNetwork.read () := by
  constructor
  · rw [ruleOf_eq_top, ruleOf_eq_top]
    rfl
  · simp [falseNetwork, trueNetwork]

/-! ## §4 — Interaction shapes latent memory and connection -/

/-- An interaction translates readings, remains in the shared field, and commutes with moral
admission. -/
structure Interaction (N : Network) where
  translate : N.Reading → N.Reading
  admissible : ∀ {r}, r ∈ N.shared → translate r ∈ N.shared
  moral_natural : ∀ r, translate (N.admits r) = N.admits (translate r)

/-- Latent memory is successive admissible interaction. -/
def memory {N : Network} (xs : List (Interaction N)) (r : N.Reading) : N.Reading :=
  xs.foldl (fun a i => i.translate a) r

theorem memory_admissible {N : Network} (xs : List (Interaction N))
    {r : N.Reading} (hr : r ∈ N.shared) : memory xs r ∈ N.shared := by
  induction xs generalizing r with
  | nil => exact hr
  | cons i xs ih =>
      exact ih (i.admissible hr)

theorem memory_admits {N : Network} (xs : List (Interaction N)) (r : N.Reading) :
    memory xs (N.admits r) = N.admits (memory xs r) := by
  induction xs generalizing r with
  | nil => rfl
  | cons i xs ih =>
      simpa [memory, i.moral_natural] using ih (i.translate r)

/-- A connection retains which interactions occurred while forgetting their temporal ordering. -/
def connection {N : Network} (xs : List (Interaction N)) : Multiset (Interaction N) :=
  xs

theorem conn_append {N : Network} (xs ys : List (Interaction N)) :
    connection (xs ++ ys) = connection xs + connection ys := by
  simp [connection]

theorem conn_subset_append {N : Network} (xs ys : List (Interaction N)) :
    connection xs ≤ connection (xs ++ ys) := by
  rw [conn_append]
  exact Multiset.le_add_right _ _

theorem conn_of_perm {N : Network} {xs ys : List (Interaction N)} (h : xs.Perm ys) :
    connection xs = connection ys := by
  exact Quotient.sound h

/-! ## §5 — Super-network translations and the one unity -/

/-- A translation carries sites and readings while preserving readout, culture, and admission. -/
structure Translation (N M : Network) where
  onSite : N.Site → M.Site
  onReading : N.Reading → M.Reading
  read_natural : ∀ s, onReading (N.read s) = M.read (onSite s)
  shared_map : ∀ {r}, r ∈ N.shared → onReading r ∈ M.shared
  admits_natural : ∀ r, onReading (N.admits r) = M.admits (onReading r)

namespace Translation

def id (N : Network) : Translation N N where
  onSite := fun s => s
  onReading := fun r => r
  read_natural := by intro; rfl
  shared_map := by intro _ h; exact h
  admits_natural := by intro; rfl

def comp {N M K : Network} (g : Translation M K) (f : Translation N M) :
    Translation N K where
  onSite := g.onSite ∘ f.onSite
  onReading := g.onReading ∘ f.onReading
  read_natural := by
    intro s
    simp only [Function.comp_apply, f.read_natural, g.read_natural]
  shared_map := by
    intro r hr
    exact g.shared_map (f.shared_map hr)
  admits_natural := by
    intro r
    simp only [Function.comp_apply, f.admits_natural, g.admits_natural]

end Translation

/-- An invertible admissible self-translation of a network. -/
structure Reinterp (N : Network) where
  siteEquiv : N.Site ≃ N.Site
  readingEquiv : N.Reading ≃ N.Reading
  read_natural : ∀ s, readingEquiv (N.read s) = N.read (siteEquiv s)
  shared_iff : ∀ r, readingEquiv r ∈ N.shared ↔ r ∈ N.shared
  admits_natural : ∀ r, readingEquiv (N.admits r) = N.admits (readingEquiv r)

namespace Reinterp

/-- A reinterpretation is itself an admissible interaction. -/
def toInteraction {N : Network} (ρ : Reinterp N) : Interaction N where
  translate := ρ.readingEquiv
  admissible := by
    intro r hr
    exact (ρ.shared_iff r).mpr hr
  moral_natural := ρ.admits_natural

private theorem symm_admits {N : Network} (ρ : Reinterp N) (r : N.Reading) :
    ρ.readingEquiv.symm (N.admits r) = N.admits (ρ.readingEquiv.symm r) := by
  apply ρ.readingEquiv.injective
  simp only [Equiv.apply_symm_apply, ρ.admits_natural]

/-- Reinterpretation carries an interaction by conjugating it inside the same shared field. -/
def carry {N : Network} (ρ : Reinterp N) (i : Interaction N) : Interaction N where
  translate r := ρ.readingEquiv (i.translate (ρ.readingEquiv.symm r))
  admissible := by
    intro r hr
    have hin : ρ.readingEquiv.symm r ∈ N.shared := by
      exact (ρ.shared_iff (ρ.readingEquiv.symm r)).mp (by simpa using hr)
    exact (ρ.shared_iff _).mpr (i.admissible hin)
  moral_natural := by
    intro r
    rw [symm_admits, i.moral_natural, ρ.admits_natural]

end Reinterp

/-- The one-point shared network. -/
def unity : Network where
  Site := Unit
  Reading := Unit
  read := fun _ => ()
  admits := Equiv.refl Unit
  shared := Set.univ
  read_shared := by simp
  admits_shared := by simp

/-- Every network has the evident translation into unity. -/
def toUnity (N : Network) : Translation N unity where
  onSite := fun _ => ()
  onReading := fun _ => ()
  read_natural := by intro; rfl
  shared_map := by
    intro r hr
    change True
    trivial
  admits_natural := by intro; rfl

private theorem translations_to_unity_equal (N : Network) (f g : Translation N unity) : f = g := by
  cases f with
  | mk fs fr fn fsh fa =>
      cases g with
      | mk gs gr gn gsh ga =>
          have hs : fs = gs := by
            funext s
            change () = ()
            rfl
          have hr : fr = gr := by
            funext r
            change () = ()
            rfl
          subst gs
          subst gr
          rfl

/-- Unity is terminal: there is exactly one translation from every network into it. -/
theorem unity_terminal (N : Network) : ∃! _t : Translation N unity, True := by
  refine ⟨toUnity N, trivial, ?_⟩
  intro _t _
  exact translations_to_unity_equal N _t (toUnity N)

/-! ## §6 — The operators derive one another relative to interaction -/

/-- The recursive run equation is exactly one application of the interactive loop. -/
theorem run_eq_stepLoop_run (L : Loop S Obs) (s : S) (n : ℕ) :
    L.run s (n + 1) = L.step (L.run s n) := rfl

/-- One interaction is one step of latent memory. -/
theorem interaction_as_one_step_memory {N : Network} (i : Interaction N) (r : N.Reading) :
    memory [i] r = i.translate r := by rfl

/-- A whole memory is itself one composed admissible interaction. -/
def memoryInteraction {N : Network} (xs : List (Interaction N)) : Interaction N where
  translate := memory xs
  admissible := by
    intro r hr
    exact memory_admissible xs hr
  moral_natural := memory_admits xs

theorem memory_as_one_interaction {N : Network} (xs : List (Interaction N)) (r : N.Reading) :
    (memoryInteraction xs).translate r = memory xs r := rfl

/-! ## §7 — A carrier-free `0`/`∞` closure -/

/-- A polar point is either the fixed unit or one of two orientations at a radius. -/
inductive PolarPoint (R : Type u) where
  | unit : PolarPoint R
  | ray (side : Bool) (radius : R) : PolarPoint R

/-- Polar reversal exchanges the two orientations and fixes the unit. -/
def polar {R : Type u} : PolarPoint R → PolarPoint R
  | .unit => .unit
  | .ray side r => .ray (!side) r

instance {R : Type u} : Inv (PolarPoint R) where
  inv := polar

@[simp] theorem polar_unit {R : Type u} : (PolarPoint.unit : PolarPoint R)⁻¹ = .unit := rfl

@[simp] theorem polar_ray {R : Type u} (side : Bool) (r : R) :
    (PolarPoint.ray side r)⁻¹ = .ray (!side) r := rfl

@[simp] theorem polar_involutive {R : Type u} (x : PolarPoint R) : x⁻¹⁻¹ = x := by
  cases x with
  | unit => rfl
  | ray side r => cases side <;> rfl

def zero {R : Type u} (r : R) : PolarPoint R := .ray false r
def infinity {R : Type u} (r : R) : PolarPoint R := .ray true r
def one {R : Type u} : PolarPoint R := .unit

/-- Closure equality identifies a point only with itself or its polar reversal. -/
def PolarRel {R : Type u} (x y : PolarPoint R) : Prop :=
  y = x ∨ y = x⁻¹

theorem polarRel_equivalence (R : Type u) : Equivalence (@PolarRel R) := by
  refine ⟨?_, ?_, ?_⟩
  · intro x
    exact Or.inl rfl
  · intro x y h
    rcases h with rfl | rfl
    · exact Or.inl rfl
    · exact Or.inr (polar_involutive x).symm
  · intro x y z hxy hyz
    rcases hxy with rfl | rfl <;> rcases hyz with rfl | rfl
    · exact Or.inl rfl
    · exact Or.inr rfl
    · exact Or.inr rfl
    · exact Or.inl (polar_involutive x)

def polarSetoid (R : Type u) : Setoid (PolarPoint R) where
  r := PolarRel
  iseqv := polarRel_equivalence R

/-- The two named poles are literally related by polar closure. -/
theorem zero_rel_top {R : Type u} (r : R) : PolarRel (zero r) (infinity r) :=
  Or.inr rfl

/-- Radius forgets orientation but retains the fixed unit as `none`. -/
def radius {R : Type u} : PolarPoint R → Option R
  | .unit => none
  | .ray _ r => some r

/-- Polar closure and equality of radii are the same relation. -/
theorem rel_iff_radius {R : Type u} (x y : PolarPoint R) :
    PolarRel x y ↔ radius x = radius y := by
  cases x with
  | unit =>
      cases y <;> simp [PolarRel, radius]
  | ray sx rx =>
      cases y with
      | unit => simp [PolarRel, radius]
      | ray sy ry =>
          cases sx <;> cases sy <;> simp [PolarRel, radius, eq_comm]

/-- The numeric `0`/`∞` quotient. -/
abbrev ZeroInfClosure (R : Type u) := Quotient (polarSetoid R)

def closureRadius {R : Type u} : ZeroInfClosure R → Option R :=
  Quotient.lift radius (fun x y h => (rel_iff_radius x y).mp h)

private def radiusPoint {R : Type u} : Option R → PolarPoint R
  | none => .unit
  | some r => zero r

/-- Quotienting the two orientations yields one optional-radius continuum. -/
def zeroInfClosureEquiv (R : Type u) : ZeroInfClosure R ≃ Option R where
  toFun := closureRadius
  invFun o := Quotient.mk (polarSetoid R) (radiusPoint o)
  left_inv q := by
    refine Quotient.inductionOn q ?_
    intro x
    apply Quotient.sound
    apply (rel_iff_radius _ _).mpr
    cases x <;> rfl
  right_inv o := by
    cases o <;> rfl

private def polarEquiv (R : Type u) : PolarPoint R ≃ PolarPoint R where
  toFun := polar
  invFun := polar
  left_inv := polar_involutive
  right_inv := polar_involutive

/-- The two poles, as one shared network. -/
def polesNetwork {R : Type u} (r : R) : Network where
  Site := Bool
  Reading := PolarPoint R
  read b := if b then infinity r else zero r
  admits := polarEquiv R
  shared := Set.univ
  read_shared := by simp
  admits_shared := by simp

theorem poles_admissible {R : Type u} (r : R) (b : Bool) :
    (polesNetwork r).admits ((polesNetwork r).read b) ∈ (polesNetwork r).shared := by
  trivial

/-! ## Problems are real; solutions are interactions -/

/-- A real problem is a reading already situated in the shared field. -/
abbrev RealProblem (N : Network) := {r : N.Reading // r ∈ N.shared}

/-- A solution is an admissible interaction, not an externally supplied rule. -/
abbrev Solution (N : Network) := Interaction N

theorem solutions_are_interactions (N : Network) : Solution N = Interaction N := rfl

/-- The seven-section answer: continuation resists finite verdicts; authorship collapses potential;
the network admits all its sites; interactions preserve shared memory; unity is terminal; the two
poles close; and solutions are exactly interactions. -/
theorem nrrf764_answer (n : ℕ) (I : Ind) (a : I.Det) (N : Network)
    (xs : List (Interaction N)) (r : N.Reading) (hr : r ∈ N.shared)
    {R : Type u} (p : R) :
    (¬ ∃ test : (Fin n → Bool) → Prop, Loop.CorrectFiniteHaltingTest n test) ∧
    (∃! d : I.Det, d ∈ Ind.authorship a) ∧
    ruleOf N = Set.univ ∧
    memory xs r ∈ N.shared ∧
    (∃! _t : Translation N unity, True) ∧
    PolarRel (zero p) (infinity p) ∧
    Solution N = Interaction N := by
  exact ⟨Loop.no_finite_halting_test n, Ind.det_globalCollapse_unique a,
    ruleOf_eq_top N, memory_admissible xs hr, unity_terminal N,
    zero_rel_top p, solutions_are_interactions N⟩

#print axioms NRRF764.nrrf764_answer

end NRRF764
