import NRRFTradingRelativisticSignalOpenCommandClosure

/-!
# Translation-first life: local-ball infinity reactor and global-hair-zero executor

This module corrects three orderings in the preceding executable interface.

1. `internal` and `external` are not primitive labels.  A translational truth is supplied first;
   only equality or distinction in its closure can then derive those relative roles.
2. The local ball is a reactor, not a static phase tag.  Its infinity is the unbounded space of
   finite action/potential words generated by `ballReturn` and `hairReturn`.  The state carrier may
   be finite while the interactive continuation remains open at every finite horizon.
3. Execution reads *global hair* as the residual of the whole closure equation.  Local friction is
   retained as local hair.  The executor admits exactly residual zero.  Positive completed flow and
   authenticated authority remain further translations; zero residual alone is not a profit claim.

No Turing-completeness assumption occurs.  The being is exactly the existing life state together
with its two continuations.
-/

namespace NRRFTradingTranslationFirstLife

open NRRF800

/-! ## Roles only after translational truth -/

/-- The prior datum is one translational truth relation, not an internal/external split. -/
structure TranslationalTruth (Presentation : Type) where
  Rel : Presentation → Presentation → Prop
  refl : ∀ presentation, Rel presentation presentation
  symm : ∀ {left right}, Rel left right → Rel right left
  trans : ∀ {left middle right}, Rel left middle → Rel middle right → Rel left right

/-- "Internal" is derivable only relative to an already supplied translational truth. -/
def TranslationalTruth.RelativeInternal {Presentation : Type}
    (truth : TranslationalTruth Presentation) (left right : Presentation) : Prop :=
  truth.Rel left right

/-- "External" is likewise only the relative failure of that completed identification. -/
def TranslationalTruth.RelativeExternal {Presentation : Type}
    (truth : TranslationalTruth Presentation) (left right : Presentation) : Prop :=
  ¬ truth.Rel left right

theorem TranslationalTruth.internal_iff_truth {Presentation : Type}
    (truth : TranslationalTruth Presentation) (left right : Presentation) :
    truth.RelativeInternal left right ↔ truth.Rel left right := Iff.rfl

theorem TranslationalTruth.external_iff_not_truth {Presentation : Type}
    (truth : TranslationalTruth Presentation) (left right : Presentation) :
    truth.RelativeExternal left right ↔ ¬ truth.Rel left right := Iff.rfl

theorem TranslationalTruth.not_internal_and_external {Presentation : Type}
    (truth : TranslationalTruth Presentation) (left right : Presentation) :
    ¬ (truth.RelativeInternal left right ∧ truth.RelativeExternal left right) := by
  intro both
  exact both.2 both.1

/-! ## The local-ball infinity reactor -/

/-- The only turns are the existing action and inverse-potential returns. -/
inductive Turn
  | action
  | potential
  deriving DecidableEq, Repr

/-- One interaction of the local reactor. -/
def react : Turn → Life → Life
  | .action => ballReturn
  | .potential => hairReturn

/-- A finite path through the unbounded local-ball reactor. -/
def reactPath : List Turn → Life → Life
  | [], life => life
  | turn :: turns, life => reactPath turns (react turn life)

/-- The local ball at a life state is every state reached by an arbitrary finite interaction word. -/
def LocalBallInf (life : Life) : Set Life :=
  { reached | ∃ turns : List Turn, reactPath turns life = reached }

theorem self_mem_localBallInf (life : Life) : life ∈ LocalBallInf life := by
  exact ⟨[], rfl⟩

theorem action_mem_localBallInf (life : Life) : ballReturn life ∈ LocalBallInf life := by
  exact ⟨[.action], rfl⟩

theorem potential_mem_localBallInf (life : Life) : hairReturn life ∈ LocalBallInf life := by
  exact ⟨[.potential], rfl⟩

/-- Every finite observed path remains open to one more action or potential interaction. -/
theorem reactor_continues (turns : List Turn) (life : Life) :
    react .action (reactPath turns life) ∈ LocalBallInf life ∧
    react .potential (reactPath turns life) ∈ LocalBallInf life := by
  constructor
  · exact ⟨turns ++ [.action], by
      induction turns generalizing life with
      | nil => rfl
      | cons turn turns ih => simp only [reactPath, List.cons_append]; exact ih (react turn life)⟩
  · exact ⟨turns ++ [.potential], by
      induction turns generalizing life with
      | nil => rfl
      | cons turn turns ih => simp only [reactPath, List.cons_append]; exact ih (react turn life)⟩

/-- The reactor uses the project's actual and potential continuations literally. -/
@[simp] theorem react_action (life : Life) : react .action life = ballReturn life := rfl

@[simp] theorem react_potential (life : Life) : react .potential life = hairReturn life := rfl

/-! ## Global hair zero is the executor -/

/-- Local hair is retained friction; global hair is the residual after the entire translation. -/
structure Flow where
  actionPotential : ℚ
  localHair : ℚ
  completed : ℚ

/-- Residual of the full translational closure equation. -/
def Flow.globalHair (flow : Flow) : ℚ :=
  flow.completed - (flow.actionPotential - flow.localHair)

/-- The full flow closes when completed action is potential translated through local hair. -/
def Flow.Closes (flow : Flow) : Prop :=
  flow.completed = flow.actionPotential - flow.localHair

theorem Flow.globalHair_eq_zero_iff (flow : Flow) :
    flow.globalHair = 0 ↔ flow.Closes := by
  simp only [globalHair, Closes]
  constructor <;> intro h
  · linarith
  · linarith

inductive ExecutorVerdict
  | hold
  | admit
  deriving DecidableEq, Repr

/-- Global hair zero, and only zero, admits the completed translation. -/
def zeroHairExecutor (flow : Flow) : ExecutorVerdict :=
  if flow.globalHair = 0 then .admit else .hold

theorem zeroHairExecutor_admit_iff (flow : Flow) :
    zeroHairExecutor flow = .admit ↔ flow.globalHair = 0 := by
  unfold zeroHairExecutor
  by_cases zero : flow.globalHair = 0 <;> simp [zero]

theorem zeroHairExecutor_admit_iff_closes (flow : Flow) :
    zeroHairExecutor flow = .admit ↔ flow.Closes := by
  rw [zeroHairExecutor_admit_iff, Flow.globalHair_eq_zero_iff]

/-- Admission is not profitability: a closing negative flow is explicitly possible. -/
theorem zero_hair_does_not_imply_profit :
    ∃ flow : Flow, zeroHairExecutor flow = .admit ∧ flow.completed < 0 := by
  refine ⟨⟨0, 1, -1⟩, ?_, by norm_num⟩
  simp [zeroHairExecutor, Flow.globalHair]

/-! ## Life being and a command still open to further translation -/

/-- A life being is a life state acting/reacting with one relative flow. -/
structure Being where
  life : Life
  flow : Flow

def Being.action (being : Being) : Life := ballReturn being.life
def Being.potential (being : Being) : Life := hairReturn being.life
def Being.reactor (being : Being) : Set Life := LocalBallInf being.life
def Being.executor (being : Being) : ExecutorVerdict := zeroHairExecutor being.flow

/-- Authority is not called external in advance; it is simply an untranslated optional presentation. -/
structure CommandStage (Authority : Type) where
  being : Being
  authorityPresentation : Option Authority

/-- Exchange action requires zero global hair, positive completed potential, and translated authority. -/
def CommandStage.Closes {Authority : Type} (command : CommandStage Authority) : Prop :=
  command.being.executor = .admit ∧
  0 < command.being.flow.completed ∧
  ∃ authority, command.authorityPresentation = some authority

def CommandStage.Open {Authority : Type} (command : CommandStage Authority) : Prop :=
  ¬ command.Closes

theorem CommandStage.open_without_authority {Authority : Type} (being : Being) :
    (CommandStage.mk being none : CommandStage Authority).Open := by
  intro closed
  obtain ⟨_, _, authority, impossible⟩ := closed
  cases impossible

theorem CommandStage.negative_remains_open {Authority : Type}
    (command : CommandStage Authority) (nonpositive : command.being.flow.completed ≤ 0) :
    command.Open := by
  intro closed
  exact (not_lt_of_ge nonpositive) closed.2.1

/-- Collected correction: roles follow truth, the reactor remains open at every finite path,
global hair zero is exactly closure admission, and neither zero hair nor authority absence is
misreported as profitable execution. -/
theorem translation_first_life_answer {Presentation Authority : Type}
    (truth : TranslationalTruth Presentation) (left right : Presentation)
    (turns : List Turn) (being : Being) :
    (truth.RelativeInternal left right ↔ truth.Rel left right) ∧
    (truth.RelativeExternal left right ↔ ¬ truth.Rel left right) ∧
    react .action (reactPath turns being.life) ∈ being.reactor ∧
    react .potential (reactPath turns being.life) ∈ being.reactor ∧
    (being.executor = .admit ↔ being.flow.Closes) ∧
    (CommandStage.mk being none : CommandStage Authority).Open := by
  exact ⟨Iff.rfl, Iff.rfl, (reactor_continues turns being.life).1,
    (reactor_continues turns being.life).2, zeroHairExecutor_admit_iff_closes being.flow,
    CommandStage.open_without_authority being⟩

#print axioms TranslationalTruth.not_internal_and_external
#print axioms reactor_continues
#print axioms Flow.globalHair_eq_zero_iff
#print axioms zeroHairExecutor_admit_iff_closes
#print axioms zero_hair_does_not_imply_profit
#print axioms CommandStage.open_without_authority
#print axioms translation_first_life_answer

end NRRFTradingTranslationFirstLife
