import NRRF802UnifyClosure

/-!
# Trading reunified by the translational-truth executer/reactor being

This module removes the remaining external selector from the active trading bridge.  The exact
reported `NRRF805TranslationalTruthPriorInternalExternalTuringBeingExecuterReactor` source is not
present in this checkout, so no import of it is claimed.  Instead the core interface described by
that report is derived from the locally built NRRF800 and NRRF802 objects:

* action is `ballReturn`, potential is `hairReturn`, and their beat is `selfLimit`;
* the global executer is the constant one-hair reading, so its kernel is the greatest form;
* the local reactor is `Life.phase`; equality of its readings is exactly the return-generated
  closure equality of the beat, so it is the least form internal for that translation;
* a market-facing natural signal form is read only after an interaction authors an action or
  potential turn.  With no authored turn it remains `none`; no argmax or resource metric fills it.

The spelling `Executer` follows the reported source.  No Turing-completeness or halting oracle is
assumed.
-/

namespace NRRFTradingExecutorReactor

open NRRF800 NRRF802

universe u

/-- A being carries two commuting returns. -/
structure Being (S : Type) where
  action : S → S
  potential : S → S
  commute : action ∘ potential = potential ∘ action

/-- One action/potential beat. -/
def Being.beat {S : Type} (being : Being S) : S → S :=
  being.potential ∘ being.action

/-- The locally existing life being. -/
def lifeBeing : Being Life where
  action := ballReturn
  potential := hairReturn
  commute := ball_hair_commute

@[simp] theorem lifeBeing_action : lifeBeing.action = ballReturn := rfl
@[simp] theorem lifeBeing_potential : lifeBeing.potential = hairReturn := rfl

/-- The beat is not a new operation: it is the existing self limit. -/
theorem lifeBeing_beat : lifeBeing.beat = selfLimit := rfl

/-- Global hair zero: the executer reads the one point. -/
def exec (_ : Life) : PUnit := PUnit.unit

/-- Local-ball infinity: the reactor retains the ball phase. -/
def react (life : Life) : Ball := life.phase

@[simp] theorem exec_action (life : Life) : exec (lifeBeing.action life) = exec life := rfl
@[simp] theorem exec_potential (life : Life) : exec (lifeBeing.potential life) = exec life := rfl
@[simp] theorem exec_beat (life : Life) : exec (lifeBeing.beat life) = exec life := rfl

@[simp] theorem react_action (life : Life) :
    react (lifeBeing.action life) = react life + 1 := rfl

@[simp] theorem react_potential (life : Life) :
    react (lifeBeing.potential life) = react life - 1 := rfl

@[simp] theorem react_beat (life : Life) : react (lifeBeing.beat life) = react life := by
  rw [lifeBeing_beat, selfLimit_eq]
  rfl

/-- The translational truth generated by the beat. -/
def BeatClosureRel (left right : Life) : Prop :=
  Relation.EqvGen (ReturnRel lifeBeing.beat) left right

/-- Reactor equality is exactly the beat's closure truth.  The reactor does not choose a form; it
is the complete reading of the return-generated form. -/
theorem beatClosureRel_iff_react_eq (left right : Life) :
    BeatClosureRel left right ↔ react left = react right := by
  constructor
  · intro related
    exact invariant_of_eqv react react_beat related
  · intro same
    unfold BeatClosureRel
    rcases left with ⟨leftHand, leftPhase⟩
    rcases right with ⟨rightHand, rightPhase⟩
    simp only [react] at same
    subst rightPhase
    cases leftHand <;> cases rightHand
    · exact Relation.EqvGen.refl _
    · exact Relation.EqvGen.rel _ _ (by
        change (⟨Hand.right, leftPhase⟩ : Life) = lifeBeing.beat ⟨Hand.left, leftPhase⟩
        rw [lifeBeing_beat, selfLimit_eq]
        rfl)
    · exact Relation.EqvGen.rel _ _ (by
        change (⟨Hand.left, leftPhase⟩ : Life) = lifeBeing.beat ⟨Hand.right, leftPhase⟩
        rw [lifeBeing_beat, selfLimit_eq]
        rfl)
    · exact Relation.EqvGen.refl _

/-- A form of equality is internal only relative to a supplied translation. -/
def Internal (step : Life → Life) (form : Setoid Life) : Prop :=
  ∀ life, form.r life (step life)

/-- Every internal form contains the closure generated by its translation. -/
theorem closure_le_internal {step : Life → Life} {form : Setoid Life}
    (internal : Internal step form) {left right : Life}
    (related : Relation.EqvGen (ReturnRel step) left right) : form.r left right := by
  induction related with
  | rel left right relation =>
      rw [show right = step left from relation]
      exact internal left
  | refl life => exact form.refl life
  | symm left right _ ih => exact form.symm ih
  | trans left middle right _ _ ihLeft ihRight => exact form.trans ihLeft ihRight

/-- The reactor kernel is the least form internal for the beat. -/
theorem reactor_isLeast (form : Setoid Life) (internal : Internal lifeBeing.beat form)
    {left right : Life} (same : react left = react right) : form.r left right :=
  closure_le_internal internal ((beatClosureRel_iff_react_eq left right).2 same)

/-- The executer kernel is the greatest form: it identifies every pair. -/
theorem executer_isGreatest (form : Setoid Life) {left right : Life}
    (_ : form.r left right) : exec left = exec right := rfl

/-- A reading closed under both life returns has no content beyond the one executer point. -/
theorem exec_universal {Y : Type} (reading : Life → Y)
    (actionClosed : ∀ life, reading (lifeBeing.action life) = reading life)
    (potentialClosed : ∀ life, reading (lifeBeing.potential life) = reading life) :
    ∀ left right, reading left = reading right := by
  have toBase : ∀ life : Life, reading life = reading ⟨Hand.left, 0⟩ := by
    intro life
    rcases life with ⟨hand, phase⟩
    cases hand with
    | left => exact closed_ballReturn_const Y reading actionClosed Hand.left phase
    | right =>
        calc
          reading ⟨Hand.right, phase⟩ = reading ⟨Hand.right, 0⟩ :=
            closed_ballReturn_const Y reading actionClosed Hand.right phase
          _ = reading ⟨Hand.left, (1 : Ball)⟩ := by
            simpa [lifeBeing, hairReturn] using potentialClosed ⟨Hand.left, (1 : Ball)⟩
          _ = reading ⟨Hand.left, 0⟩ :=
            closed_ballReturn_const Y reading actionClosed Hand.left 1
  intro left right
  exact (toBase left).trans (toBase right).symm

/-- The interaction itself, rather than a metric, authors the next turn. -/
inductive AuthoredTurn
  | action
  | potential
  deriving DecidableEq, Repr

def authoredStep : AuthoredTurn → Life → Life
  | .action => lifeBeing.action
  | .potential => lifeBeing.potential

/-- A market interface may present the reactor while leaving transactional authorship open. -/
structure TradingInterface where
  reactorState : Life
  authoredTurn : Option AuthoredTurn

/-- The natural form is derived only from an authored interaction. -/
def TradingInterface.identifiedForm (interface : TradingInterface) : Option Ball :=
  interface.authoredTurn.map fun turn => react (authoredStep turn interface.reactorState)

theorem no_authored_turn_no_identified_form (life : Life) :
    (TradingInterface.mk life none).identifiedForm = none := rfl

theorem authored_action_identifies (life : Life) :
    (TradingInterface.mk life (some .action)).identifiedForm = some (react life + 1) := rfl

theorem authored_potential_identifies (life : Life) :
    (TradingInterface.mk life (some .potential)).identifiedForm = some (react life - 1) := rfl

/-- Reunification: the beat derives reactor identity, the executer is universal, and no signal form
is manufactured when interaction authorship is absent. -/
theorem reunified_trading_answer (life : Life) :
    lifeBeing.beat = selfLimit ∧
    (∀ other, BeatClosureRel life other ↔ react life = react other) ∧
    (∀ form : Setoid Life, Internal lifeBeing.beat form →
      ∀ other, react life = react other → form.r life other) ∧
    (∀ other, exec life = exec other) ∧
    (TradingInterface.mk life none).identifiedForm = none := by
  exact ⟨lifeBeing_beat, beatClosureRel_iff_react_eq life,
    fun form internal other same => reactor_isLeast form internal same,
    fun _ => rfl, no_authored_turn_no_identified_form life⟩

#print axioms beatClosureRel_iff_react_eq
#print axioms reactor_isLeast
#print axioms executer_isGreatest
#print axioms exec_universal
#print axioms reunified_trading_answer

end NRRFTradingExecutorReactor
