import Mathlib.Tactic.NormNum

/-!
# NRRF627 — The closure translational framework, extracted

**This module is self-contained.**  It imports only Mathlib's `NormNum` entry point, redefines from scratch every
notion it uses, and proves every statement it makes.  It is the extraction of the *closure
translational framework* that had accumulated across the `NRRF6xx` kernel, together with its three
consequences: for **axiometry**, for **ASI** (a system that improves its own means of expression),
and for **evolutionary verification**.

The companion prose document is `CLOSURE_TRANSLATIONAL_FRAMEWORK.md`; every claim made there is a
theorem below.

## The framework in one paragraph

A *closure language* is not a set of true sentences but a *verification return*: a map `W` sending
an occurrence (an expression, a state, a measurement, a phase of a computation) to the relational
identity it returns.  Two occurrences are *closure-equal* when they return the same identity —
`CEq W u v : W u = W v` — and that, not syntactic identity, is the only verdict a language issues.
Languages are compared only *pairwise*, by translations `(phi, T, pi)` obeying identity and
coherence laws, so the comparison is a groupoid and **no language is the origin**.  Each language
carries two internal restructurings that closure cannot see: the polar reversal `J` (exchange of
the two orientations `0`/`∞`) and the unitary-curvature partition `C`.  Both are natural for
translation.

## Contents

* **§1 Poles and alternating order.**  `Pole`, `Pole.other`, `Alternating`, `ClosureLoop`,
  `translational_order_reveals_identity` — identity of a pole is the parity of the translation
  between two positions of a `0`/`∞` path with no `00` and no `∞∞`.
* **§2 The framework.**  `CEq`, `TransFrame`, invertibility of translation,
  `temporary_origin_cancels`.
* **§3 Closure equality is translation-invariant.**  `ceq_iff`, preserved *and* reflected with no
  extra hypothesis; `poles_closure_equal`.
* **§4 Axiometry.**  `Invariant`, `RespectsClosure`, `MeasuredByReturn`, and the characterisation
  `axiometric_verdict_characterisation`: *a verdict is language-independent and closure-respecting
  exactly when it is a measurement of the return.*  Consequences: `closure_blind_to_reversal`,
  `no_origin_language`, `no_verdict_disagreement`.
* **§5 ASI.**  Internal restructurings (`Restructuring`), the free ones generated by `J` and `C`
  (`Move`, `run`), `capability_is_gauge`, `self_improvement_preserves_verdicts`,
  `reexpression_preserves_verdicts`; and the two limits: `return_not_faithful` (verification
  underdetermines the occurrence) and `residue_is_parity` (the invisible residue is readable only
  as a `ℤ/2` parity, and that reading is language-independent).
* **§6 Evolutionary verification.**  `route` (a history through intermediate languages) with
  `route_eq_direct` — no path dependence; `evolve` over generations with `verification_heritable`,
  `verdict_conserved`, `neutral_drift`; and
  `evolutionary_verification_is_exactly_return_measurement`.
* **§7 Models.**  `standardFrame`, `flipFrame` (orientation genuinely reversed by translation:
  `flip_pi_nontrivial`), `witnessFrame` (separated, with a non-injective return).
* **§8 The bundled statement** `closure_translational_framework`.
-/

namespace NRRF627

open Function

universe u v w

/-! ## §1  The two poles and the alternating translational order -/

/-- The two poles of a closure language.  Nothing distinguishes them intrinsically; only the
exchange `Pole.other` relates one to the other. -/
inductive Pole where
  | zero : Pole
  | inf : Pole
deriving DecidableEq, Repr

namespace Pole

/-- The exchange of the two poles. -/
def other : Pole → Pole
  | zero => inf
  | inf => zero

@[simp] theorem other_other (p : Pole) : other (other p) = p := by cases p <;> rfl

theorem other_ne (p : Pole) : other p ≠ p := by cases p <;> simp [other]

/-- Identity of a pole is only ever stated relative to the other one. -/
theorem ne_iff (p q : Pole) : p ≠ q ↔ q = other p := by
  cases p <;> cases q <;> simp [other]

end Pole

/-- A `0`/`∞` path with no `00` and no `∞∞`. -/
def Alternating (c : ℕ → Pole) : Prop := ∀ i, c (i + 1) ≠ c i

/-- An alternating path that closes after `n` translations, wrap-around included. -/
structure ClosureLoop (n : ℕ) (c : ℕ → Pole) : Prop where
  pos : 0 < n
  closes : ∀ i, c (i + n) = c i
  alternating : Alternating c

theorem alt_formula {c : ℕ → Pole} (h : Alternating c) (i : ℕ) :
    c i = if Even i then c 0 else Pole.other (c 0) := by
  induction i with
  | zero => simp
  | succ i ih =>
      have hne : c (i + 1) ≠ c i := h i
      rcases Nat.even_or_odd i with he | ho
      · have : c i = c 0 := by rw [ih]; simp [he]
        rw [this] at hne
        have := (Pole.ne_iff (c 0) (c (i + 1))).1 (Ne.symm hne)
        simp [Nat.even_add_one, he, this]
      · have hno : ¬ Even i := Nat.not_even_iff_odd.2 ho
        have : c i = Pole.other (c 0) := by rw [ih]; simp [hno]
        rw [this] at hne
        have := (Pole.ne_iff (Pole.other (c 0)) (c (i + 1))).1 (Ne.symm hne)
        simp [Nat.even_add_one, hno, this]

/-- **The translational order reveals identity.**  Two positions of an alternating path carry the
same pole exactly when the translation between them is even. -/
theorem translational_order_reveals_identity {c : ℕ → Pole} (h : Alternating c) (i k : ℕ) :
    c (i + k) = c i ↔ Even k := by
  rw [alt_formula h (i + k), alt_formula h i]
  rcases Nat.even_or_odd i with hi | hi <;> rcases Nat.even_or_odd k with hk | hk <;>
    simp [Nat.even_add, hi, hk, Nat.not_even_iff_odd.2, Pole.other_ne,
      Ne.symm (Pole.other_ne (c 0))]

/-- A path with no `00` and no `∞∞` closes only in even length. -/
theorem closureLoop_even {n : ℕ} {c : ℕ → Pole} (h : ClosureLoop n c) : Even n :=
  (translational_order_reveals_identity h.alternating 0 n).1 (by simpa using h.closes 0)

/-! ## §2  The framework -/

/-- **Closure-relative equality**: two occurrences are equal for a language exactly when its
verification return sends them to the same relational identity. -/
def CEq {X : Type*} {B : Type*} (W : X → B) (x y : X) : Prop := W x = W y

theorem ceq_equivalence {X B : Type*} (W : X → B) : Equivalence (CEq W) :=
  ⟨fun _ => rfl, fun h => h.symm, fun h₁ h₂ => h₁.trans h₂⟩

/-- Every permutation of the two poles commutes with the exchange: an orientation relabelling can
never break the polar symmetry. -/
theorem perm_comm_other (s : Equiv.Perm Pole) (p : Pole) :
    s (Pole.other p) = Pole.other (s p) := by
  have h : s (Pole.other p) ≠ s p := fun hc => (Pole.other_ne p) (s.injective hc)
  exact (Pole.ne_iff _ _).1 (Ne.symm h)

/-- **The closure translational framework.**

A family of admitted closure languages indexed by `L`.  Each language `ℓ` has its own basis `B ℓ`
of relational identities, its own type `Y ℓ` of occurrences, a verification return `W ℓ`, and the
two orientation presentations `E ℓ p` (`p = 0, ∞`) which the return recovers.  Languages are
compared by *pairwise* translations: a basis map `phi ℓ m`, an occurrence map `T ℓ m` and an
orientation relabelling `pi ℓ m`, all obeying identity and coherence laws — so the comparison is a
groupoid and no language is the origin.  Each language also carries the two internal restructurings
of the polar closure: the reversal `J ℓ` (opposite contact) and the unitary-curvature partition
`C ℓ`.  Both are invisible to the return and natural for translation. -/
structure TransFrame (L : Type u) (B : L → Type v) (Y : L → Type w) where
  /-- the verification return of each language -/
  W : ∀ ℓ, Y ℓ → B ℓ
  /-- the orientation presentations of each language -/
  E : ∀ ℓ, Pole → B ℓ → Y ℓ
  /-- both presentations are returned to the identity they present -/
  recov : ∀ ℓ p b, W ℓ (E ℓ p b) = b
  /-- translation of relational identities -/
  phi : ∀ ℓ m, B ℓ → B m
  /-- an unchanged expression is not translated -/
  phi_id : ∀ ℓ b, phi ℓ ℓ b = b
  /-- coherence of basis translation -/
  phi_comp : ∀ ℓ m k b, phi m k (phi ℓ m b) = phi ℓ k b
  /-- translation of occurrences -/
  T : ∀ ℓ m, Y ℓ → Y m
  /-- an unchanged expression is not translated -/
  T_id : ∀ ℓ u, T ℓ ℓ u = u
  /-- coherence of occurrence translation -/
  T_comp : ∀ ℓ m k u, T m k (T ℓ m u) = T ℓ k u
  /-- the return square: translated verification is verified translation -/
  T_ret : ∀ ℓ m u, W m (T ℓ m u) = phi ℓ m (W ℓ u)
  /-- orientation relabelling: preserve or reverse, never a third pole -/
  pi : L → L → Equiv.Perm Pole
  /-- an unchanged expression does not relabel orientations -/
  pi_id : ∀ ℓ, pi ℓ ℓ = Equiv.refl Pole
  /-- coherence of the orientation relabelling -/
  pi_comp : ∀ ℓ m k p, pi m k (pi ℓ m p) = pi ℓ k p
  /-- the orientation law: presentations translate to presentations -/
  T_ext : ∀ ℓ m p b, T ℓ m (E ℓ p b) = E m (pi ℓ m p) (phi ℓ m b)
  /-- the polar reversal (opposite contact) of each language -/
  J : ∀ ℓ, Y ℓ → Y ℓ
  /-- reversal is an involution -/
  J_invol : ∀ ℓ u, J ℓ (J ℓ u) = u
  /-- reversal is invisible to the return -/
  J_ret : ∀ ℓ u, W ℓ (J ℓ u) = W ℓ u
  /-- on presentations, reversal is the exchange of the poles -/
  J_ext : ∀ ℓ p b, J ℓ (E ℓ p b) = E ℓ (Pole.other p) b
  /-- reversal is natural for translation -/
  T_J : ∀ ℓ m u, T ℓ m (J ℓ u) = J m (T ℓ m u)
  /-- the representative map of the unitary-curvature partition -/
  C : ∀ ℓ, Y ℓ → Y ℓ
  /-- the partition representative is idempotent -/
  C_idem : ∀ ℓ u, C ℓ (C ℓ u) = C ℓ u
  /-- the partition is invisible to the return -/
  C_ret : ∀ ℓ u, W ℓ (C ℓ u) = W ℓ u
  /-- the partition is natural for translation -/
  T_C : ∀ ℓ m u, T ℓ m (C ℓ u) = C m (T ℓ m u)

namespace TransFrame

variable {L : Type u} {B : L → Type v} {Y : L → Type w} (A : TransFrame L B Y)

/-- Translation of occurrences is invertible: the translation back is its inverse. -/
def transEquiv (ℓ m : L) : Y ℓ ≃ Y m where
  toFun := A.T ℓ m
  invFun := A.T m ℓ
  left_inv u := by rw [A.T_comp, A.T_id]
  right_inv u := by rw [A.T_comp, A.T_id]

@[simp] theorem T_T (ℓ m : L) (u : Y ℓ) : A.T m ℓ (A.T ℓ m u) = u := by
  rw [A.T_comp, A.T_id]

theorem T_injective (ℓ m : L) : Injective (A.T ℓ m) := (A.transEquiv ℓ m).injective

theorem T_bijective (ℓ m : L) : Bijective (A.T ℓ m) := (A.transEquiv ℓ m).bijective

/-- Translation of relational identities is invertible too. -/
def phiEquiv (ℓ m : L) : B ℓ ≃ B m where
  toFun := A.phi ℓ m
  invFun := A.phi m ℓ
  left_inv b := by rw [A.phi_comp, A.phi_id]
  right_inv b := by rw [A.phi_comp, A.phi_id]

@[simp] theorem phi_phi (ℓ m : L) (b : B ℓ) : A.phi m ℓ (A.phi ℓ m b) = b := by
  rw [A.phi_comp, A.phi_id]

theorem phi_injective (ℓ m : L) : Injective (A.phi ℓ m) := (A.phiEquiv ℓ m).injective

/-- **Every temporary origin cancels.**  A comparison routed through an intermediate language is
the direct comparison: choosing a language to translate *through* adds nothing. -/
theorem temporary_origin_cancels (ℓ m k : L) (u : Y ℓ) : A.T m k (A.T ℓ m u) = A.T ℓ k u :=
  A.T_comp ℓ m k u

theorem pi_pi (ℓ m : L) (p : Pole) : A.pi m ℓ (A.pi ℓ m p) = p := by
  rw [A.pi_comp, A.pi_id]; rfl

/-! ## §3  Closure equality is translation-invariant, in both directions -/

/-- **Closure equality is preserved and reflected by every translation.**  Reflection needs no
extra hypothesis: it is already contained in the groupoid law. -/
theorem ceq_iff (ℓ m : L) (u v : Y ℓ) :
    CEq (A.W ℓ) u v ↔ CEq (A.W m) (A.T ℓ m u) (A.T ℓ m v) := by
  unfold CEq
  rw [A.T_ret, A.T_ret]
  exact ⟨fun h => by rw [h], fun h => A.phi_injective ℓ m h⟩

theorem ceq_preserved {ℓ : L} (m : L) {u v : Y ℓ} (h : CEq (A.W ℓ) u v) :
    CEq (A.W m) (A.T ℓ m u) (A.T ℓ m v) := (A.ceq_iff ℓ m u v).1 h

theorem ceq_reflected_freely {ℓ m : L} {u v : Y ℓ}
    (h : CEq (A.W m) (A.T ℓ m u) (A.T ℓ m v)) : CEq (A.W ℓ) u v :=
  (A.ceq_iff ℓ m u v).2 h

/-- Both orientation presentations of one relational identity are closure-equal, in every
language: the poles are admissible, not distinguished by closure. -/
theorem poles_closure_equal (ℓ : L) (p q : Pole) (b : B ℓ) :
    CEq (A.W ℓ) (A.E ℓ p b) (A.E ℓ q b) := by
  show A.W ℓ _ = A.W ℓ _
  rw [A.recov, A.recov]

/-! ## §4  Axiometry: what a language-independent verdict can be -/

section Verdicts

variable {Ω : Type*}

/-- A verdict is *language-independent* when translating an occurrence does not change it. -/
def Invariant (Q : ∀ ℓ, Y ℓ → Ω) : Prop := ∀ ℓ m u, Q m (A.T ℓ m u) = Q ℓ u

/-- A verdict *respects closure* when it cannot separate occurrences with the same return. -/
def RespectsClosure (Q : ∀ ℓ, Y ℓ → Ω) : Prop :=
  ∀ ℓ u v, A.W ℓ u = A.W ℓ v → Q ℓ u = Q ℓ v

/-- A verdict is *a measurement of the return* when it is a translation-compatible function of the
relational identity returned, and of nothing else. -/
def MeasuredByReturn (Q : ∀ ℓ, Y ℓ → Ω) : Prop :=
  ∃ q : ∀ ℓ, B ℓ → Ω, (∀ ℓ m b, q m (A.phi ℓ m b) = q ℓ b) ∧ ∀ ℓ u, Q ℓ u = q ℓ (A.W ℓ u)

/-- **The axiometric characterisation.**  A verdict is language-independent and closure-respecting
*exactly* when it is a measurement of the verification return.  There is no third kind of
objective content: whatever survives every change of language is what closure already returned. -/
theorem axiometric_verdict_characterisation (Q : ∀ ℓ, Y ℓ → Ω) :
    (A.Invariant Q ∧ A.RespectsClosure Q) ↔ A.MeasuredByReturn Q := by
  constructor
  · rintro ⟨hinv, hresp⟩
    refine ⟨fun ℓ b => Q ℓ (A.E ℓ Pole.zero b), ?_, ?_⟩
    · intro ℓ m b
      have hpole : A.pi ℓ m ((A.pi ℓ m).symm Pole.zero) = Pole.zero := by simp
      have h1 : A.T ℓ m (A.E ℓ ((A.pi ℓ m).symm Pole.zero) b)
          = A.E m Pole.zero (A.phi ℓ m b) := by
        rw [A.T_ext, hpole]
      have h2 : Q m (A.E m Pole.zero (A.phi ℓ m b))
          = Q ℓ (A.E ℓ ((A.pi ℓ m).symm Pole.zero) b) := by
        rw [← h1]; exact hinv ℓ m _
      show Q m (A.E m Pole.zero (A.phi ℓ m b)) = Q ℓ (A.E ℓ Pole.zero b)
      rw [h2]
      exact hresp ℓ _ _ (by rw [A.recov, A.recov])
    · intro ℓ u
      exact (hresp ℓ u (A.E ℓ Pole.zero (A.W ℓ u)) (by rw [A.recov]))
  · rintro ⟨q, hq, hQ⟩
    refine ⟨?_, ?_⟩
    · intro ℓ m u
      rw [hQ, hQ, A.T_ret, hq]
    · intro ℓ u v h
      rw [hQ, hQ, h]

/-- A language-independent, closure-respecting verdict cannot see the polar reversal. -/
theorem closure_blind_to_reversal {Q : ∀ ℓ, Y ℓ → Ω} (h : A.RespectsClosure Q) (ℓ : L) (u : Y ℓ) :
    Q ℓ (A.J ℓ u) = Q ℓ u := h ℓ _ _ (A.J_ret ℓ u)

/-- Nor the unitary-curvature partition. -/
theorem closure_blind_to_curvature {Q : ∀ ℓ, Y ℓ → Ω} (h : A.RespectsClosure Q) (ℓ : L)
    (u : Y ℓ) : Q ℓ (A.C ℓ u) = Q ℓ u := h ℓ _ _ (A.C_ret ℓ u)

/-- Nor the two orientations of one identity. -/
theorem closure_blind_to_poles {Q : ∀ ℓ, Y ℓ → Ω} (h : A.RespectsClosure Q) (ℓ : L) (p q : Pole)
    (b : B ℓ) : Q ℓ (A.E ℓ p b) = Q ℓ (A.E ℓ q b) :=
  h ℓ _ _ (A.poles_closure_equal ℓ p q b)

/-- **No origin language.**  Two languages issuing a language-independent verdict never disagree:
the verdict computed in one, after translation, is the verdict computed in the other. -/
theorem no_verdict_disagreement {Q : ∀ ℓ, Y ℓ → Ω} (h : A.Invariant Q) (ℓ m : L) (u : Y ℓ) :
    Q m (A.T ℓ m u) = Q ℓ u := h ℓ m u

/-- **No origin language, second face.**  Any language may be used as the hub of a comparison and
the comparison is unchanged. -/
theorem no_origin_language (ℓ m k k' : L) (u : Y ℓ) :
    A.T m k (A.T ℓ m u) = A.T k' k (A.T ℓ k' u) := by
  rw [A.T_comp, A.T_comp]

end Verdicts

/-! ## §5  ASI: self-improvement is gauge, and its two limits -/

/-- An *internal restructuring* of the framework: a self-map of the occurrences of each language
which the return cannot see and which every translation carries.  The reversal `J`, the curvature
partition `C`, and every composite of them are examples; so is every re-encoding an agent may
perform on its own representations without changing what it verifies. -/
structure Restructuring where
  /-- the action on occurrences of each language -/
  act : ∀ ℓ, Y ℓ → Y ℓ
  /-- the return cannot see it -/
  act_ret : ∀ ℓ u, A.W ℓ (act ℓ u) = A.W ℓ u
  /-- translation carries it -/
  act_nat : ∀ ℓ m u, A.T ℓ m (act ℓ u) = act m (A.T ℓ m u)

/-- The two generating internal moves of a closure language. -/
inductive Move where
  | reversal : Move
  | curvature : Move
deriving DecidableEq, Repr

/-- The action of a single move. -/
def step (A : TransFrame L B Y) (ℓ : L) : Move → Y ℓ → Y ℓ
  | Move.reversal => A.J ℓ
  | Move.curvature => A.C ℓ

/-- The action of a finite programme of internal moves: an agent restructuring its own
representations, for as many steps as it likes. -/
def run (A : TransFrame L B Y) (ℓ : L) : List Move → Y ℓ → Y ℓ
  | [], u => u
  | s :: ms, u => run A ℓ ms (A.step ℓ s u)

@[simp] theorem run_nil (ℓ : L) (u : Y ℓ) : A.run ℓ [] u = u := rfl

@[simp] theorem run_cons (ℓ : L) (s : Move) (ms : List Move) (u : Y ℓ) :
    A.run ℓ (s :: ms) u = A.run ℓ ms (A.step ℓ s u) := rfl

theorem step_ret (ℓ : L) (s : Move) (u : Y ℓ) : A.W ℓ (A.step ℓ s u) = A.W ℓ u := by
  cases s
  · exact A.J_ret ℓ u
  · exact A.C_ret ℓ u

theorem step_nat (ℓ m : L) (s : Move) (u : Y ℓ) :
    A.T ℓ m (A.step ℓ s u) = A.step m s (A.T ℓ m u) := by
  cases s
  · exact A.T_J ℓ m u
  · exact A.T_C ℓ m u

/-- **Unbounded internal restructuring leaves the return exactly where it was.** -/
theorem run_ret (ℓ : L) (ms : List Move) (u : Y ℓ) : A.W ℓ (A.run ℓ ms u) = A.W ℓ u := by
  induction ms generalizing u with
  | nil => rfl
  | cons s ms ih => rw [run_cons, ih, A.step_ret]

theorem run_nat (ℓ m : L) (ms : List Move) (u : Y ℓ) :
    A.T ℓ m (A.run ℓ ms u) = A.run m ms (A.T ℓ m u) := by
  induction ms generalizing u with
  | nil => rfl
  | cons s ms ih => rw [run_cons, run_cons, ih, A.step_nat]

/-- Every finite programme of internal moves is an internal restructuring. -/
def runRestructuring (ms : List Move) : A.Restructuring where
  act := fun ℓ => A.run ℓ ms
  act_ret := fun ℓ u => A.run_ret ℓ ms u
  act_nat := fun ℓ m u => A.run_nat ℓ m ms u

/-- **Capability is gauge.**  No internal restructuring — however long the programme, however
sophisticated the re-encoding — changes any closure-respecting verdict. -/
theorem capability_is_gauge {Ω : Type*} {Q : ∀ ℓ, Y ℓ → Ω} (h : A.RespectsClosure Q)
    (g : A.Restructuring) (ℓ : L) (u : Y ℓ) : Q ℓ (g.act ℓ u) = Q ℓ u :=
  h ℓ _ _ (g.act_ret ℓ u)

/-- **Self-improvement preserves verdicts.**  Spelled out for a concrete programme of moves. -/
theorem self_improvement_preserves_verdicts {Ω : Type*} {Q : ∀ ℓ, Y ℓ → Ω}
    (h : A.RespectsClosure Q) (ℓ : L) (ms : List Move) (u : Y ℓ) :
    Q ℓ (A.run ℓ ms u) = Q ℓ u := h ℓ _ _ (A.run_ret ℓ ms u)

/-- **Re-expression preserves verdicts.**  An agent that invents a new language for itself, works
there, and translates back, has changed nothing: neither the occurrence nor any verdict on it. -/
theorem reexpression_preserves_verdicts {Ω : Type*} {Q : ∀ ℓ, Y ℓ → Ω}
    (hinv : A.Invariant Q) (hresp : A.RespectsClosure Q) (ℓ m : L) (ms : List Move) (u : Y ℓ) :
    A.T m ℓ (A.run m ms (A.T ℓ m u)) = A.run ℓ ms u ∧
      Q m (A.run m ms (A.T ℓ m u)) = Q ℓ u := by
  refine ⟨?_, ?_⟩
  · rw [← A.run_nat, A.T_T]
  · rw [A.self_improvement_preserves_verdicts hresp, hinv]

/-- The presentations of a language are *separated* when the two orientations of an identity are
genuinely different occurrences.  Closure still identifies them (`poles_closure_equal`). -/
def Separated : Prop := ∀ ℓ b, A.E ℓ Pole.zero b ≠ A.E ℓ Pole.inf b

/-- On a separated framework the presentation distinguishes the poles. -/
theorem E_inj_pole (hsep : A.Separated) (ℓ : L) (b : B ℓ) {p q : Pole}
    (h : A.E ℓ p b = A.E ℓ q b) : p = q := by
  cases p <;> cases q
  · rfl
  · exact absurd h (hsep ℓ b)
  · exact absurd h.symm (hsep ℓ b)
  · rfl

/-- **Verification is not faithful.**  On a separated framework the return identifies occurrences
that are not the same occurrence: no verifier, of any power, recovers the occurrence from its
verdict. -/
theorem return_not_faithful (hsep : A.Separated) (ℓ : L) (b : B ℓ) :
    ∃ u v : Y ℓ, CEq (A.W ℓ) u v ∧ u ≠ v :=
  ⟨A.E ℓ Pole.zero b, A.E ℓ Pole.inf b, A.poles_closure_equal ℓ _ _ b, hsep ℓ b⟩

/-! ### The reversal walk: the invisible residue, and the one thing readable in it -/

/-- The reversal walk of an occurrence: the `0`/`∞` path generated by iterated opposite contact. -/
def walk (ℓ : L) (u : Y ℓ) (i : ℕ) : Y ℓ := (A.J ℓ)^[i] u

@[simp] theorem walk_zero (ℓ : L) (u : Y ℓ) : A.walk ℓ u 0 = u := rfl

theorem walk_succ (ℓ : L) (u : Y ℓ) (i : ℕ) : A.walk ℓ u (i + 1) = A.J ℓ (A.walk ℓ u i) := by
  simp [walk, Function.iterate_succ_apply']

/-- Closure sees nothing of the walk: every position returns the same relational identity. -/
theorem walk_return (ℓ : L) (u : Y ℓ) (i : ℕ) : A.W ℓ (A.walk ℓ u i) = A.W ℓ u := by
  induction i with
  | zero => rfl
  | succ i ih => rw [walk_succ, A.J_ret, ih]

/-- The pole labelling of the walk started at a presentation. -/
def walkLabel (p : Pole) (i : ℕ) : Pole := Pole.other^[i] p

@[simp] theorem walkLabel_zero (p : Pole) : walkLabel p 0 = p := rfl

theorem walkLabel_succ (p : Pole) (i : ℕ) :
    walkLabel p (i + 1) = Pole.other (walkLabel p i) := by
  simp [walkLabel, Function.iterate_succ_apply']

theorem walk_ext (ℓ : L) (p : Pole) (b : B ℓ) (i : ℕ) :
    A.walk ℓ (A.E ℓ p b) i = A.E ℓ (walkLabel p i) b := by
  induction i with
  | zero => rfl
  | succ i ih => rw [walk_succ, ih, A.J_ext, walkLabel_succ]

/-- **No `00` and no `∞∞`.** -/
theorem walkLabel_alternating (p : Pole) : Alternating (walkLabel p) := by
  intro i
  rw [walkLabel_succ]
  exact Pole.other_ne _

/-- The walk labelling closes after two translations. -/
theorem walkLabel_closureLoop (p : Pole) : ClosureLoop 2 (walkLabel p) := by
  refine ⟨by norm_num, ?_, walkLabel_alternating p⟩
  intro i
  rw [show i + 2 = (i + 1) + 1 from rfl, walkLabel_succ, walkLabel_succ, Pole.other_other]

theorem walk_loop_even {n : ℕ} (p : Pole) (h : ClosureLoop n (walkLabel p)) : Even n :=
  closureLoop_even h

/-- The whole walk is carried by every translation. -/
theorem walk_translate (ℓ m : L) (u : Y ℓ) (i : ℕ) :
    A.T ℓ m (A.walk ℓ u i) = A.walk m (A.T ℓ m u) i := by
  induction i with
  | zero => rfl
  | succ i ih => rw [walk_succ, A.T_J, ih, walk_succ]

/-- The translated labelling differs from the original by the orientation relabelling and nothing
else. -/
theorem walkLabel_translate (ℓ m : L) (p : Pole) (b : B ℓ) (i : ℕ) :
    A.T ℓ m (A.walk ℓ (A.E ℓ p b) i) = A.E m (walkLabel (A.pi ℓ m p) i) (A.phi ℓ m b) := by
  rw [A.walk_ext, A.T_ext]
  congr 1
  induction i with
  | zero => rfl
  | succ i ih => rw [walkLabel_succ, walkLabel_succ, perm_comm_other, ih]

/-- **Identity along the walk is the parity of the translation.** -/
theorem walk_eq_iff_even (hsep : A.Separated) (ℓ : L) (p : Pole) (b : B ℓ) (i k : ℕ) :
    A.walk ℓ (A.E ℓ p b) (i + k) = A.walk ℓ (A.E ℓ p b) i ↔ Even k := by
  rw [A.walk_ext, A.walk_ext]
  constructor
  · intro h
    exact (translational_order_reveals_identity (walkLabel_alternating p) i k).1
      (A.E_inj_pole hsep ℓ b h)
  · intro hk
    rw [(translational_order_reveals_identity (walkLabel_alternating p) i k).2 hk]

/-- **The residue is a parity, and the parity is language-independent.**  What the return cannot
see is not thereby unreadable: identity along the reversal walk is decided by the parity of the
translation between two positions, and that verdict is the same before and after any change of
language.  It is the one piece of content an ASI can add to verification, and it is `ℤ/2`. -/
theorem residue_is_parity (hsep : A.Separated) (ℓ m : L) (p : Pole) (b : B ℓ) (i k : ℕ) :
    (A.walk ℓ (A.E ℓ p b) (i + k) = A.walk ℓ (A.E ℓ p b) i ↔ Even k) ∧
    ((A.walk ℓ (A.E ℓ p b) (i + k) = A.walk ℓ (A.E ℓ p b) i) ↔
      (A.walk m (A.E m (A.pi ℓ m p) (A.phi ℓ m b)) (i + k)
        = A.walk m (A.E m (A.pi ℓ m p) (A.phi ℓ m b)) i)) := by
  refine ⟨A.walk_eq_iff_even hsep ℓ p b i k, ?_⟩
  rw [A.walk_eq_iff_even hsep, A.walk_eq_iff_even hsep]

/-! ## §6  Evolutionary verification -/

/-- An evolutionary *history*: a translation from `ℓ` to `m` routed through a finite list of
intermediate languages. -/
def route (A : TransFrame L B Y) (ℓ : L) : List L → (m : L) → Y ℓ → Y m
  | [], m => A.T ℓ m
  | k :: ks, m => fun u => route A k ks m (A.T ℓ k u)

@[simp] theorem route_nil (ℓ m : L) (u : Y ℓ) : A.route ℓ [] m u = A.T ℓ m u := rfl

@[simp] theorem route_cons (ℓ k : L) (ks : List L) (m : L) (u : Y ℓ) :
    A.route ℓ (k :: ks) m u = A.route k ks m (A.T ℓ k u) := rfl

/-- **No path dependence.**  However long the evolutionary history, and whatever languages it
passes through, the result is the direct translation: intermediate languages leave no trace. -/
theorem route_eq_direct (ℓ : L) (ks : List L) (m : L) (u : Y ℓ) : A.route ℓ ks m u = A.T ℓ m u := by
  induction ks generalizing ℓ u with
  | nil => rfl
  | cons k ks ih => rw [route_cons, ih, A.T_comp]

/-- Two evolutionary histories with the same endpoints agree. -/
theorem history_independence (ℓ m : L) (ks ks' : List L) (u : Y ℓ) :
    A.route ℓ ks m u = A.route ℓ ks' m u := by
  rw [A.route_eq_direct, A.route_eq_direct]

/-- Generations: a sequence of languages, each obtained from the previous one by a translation. -/
def evolve (A : TransFrame L B Y) (g : ℕ → L) : (n : ℕ) → Y (g 0) → Y (g n)
  | 0 => id
  | (n + 1) => fun u => A.T (g n) (g (n + 1)) (evolve A g n u)

@[simp] theorem evolve_zero (g : ℕ → L) (u : Y (g 0)) : A.evolve g 0 u = u := rfl

@[simp] theorem evolve_succ (g : ℕ → L) (n : ℕ) (u : Y (g 0)) :
    A.evolve g (n + 1) u = A.T (g n) (g (n + 1)) (A.evolve g n u) := rfl

theorem evolve_eq_direct (g : ℕ → L) (n : ℕ) (u : Y (g 0)) :
    A.evolve g n u = A.T (g 0) (g n) u := by
  induction n with
  | zero => rw [evolve_zero, A.T_id]
  | succ n ih => rw [evolve_succ, ih, A.T_comp]

/-- **Verification is heritable, and only verification is.**  Two occurrences verify the same in
generation `0` exactly when their descendants verify the same in generation `n`: no generation can
overturn a verification verdict, and none can invent one. -/
theorem verification_heritable (g : ℕ → L) (n : ℕ) (u v : Y (g 0)) :
    CEq (A.W (g 0)) u v ↔ CEq (A.W (g n)) (A.evolve g n u) (A.evolve g n v) := by
  rw [A.evolve_eq_direct, A.evolve_eq_direct]
  exact A.ceq_iff (g 0) (g n) u v

/-- Every language-independent verdict is conserved along evolution. -/
theorem verdict_conserved {Ω : Type*} {Q : ∀ ℓ, Y ℓ → Ω} (hinv : A.Invariant Q) (g : ℕ → L)
    (n : ℕ) (u : Y (g 0)) : Q (g n) (A.evolve g n u) = Q (g 0) u := by
  rw [A.evolve_eq_direct]
  exact hinv _ _ u

/-- **Neutral drift.**  Variants that differ by internal restructuring have the same fitness for
every closure-respecting verdict — while, on a separated framework, they can still be genuinely
different occurrences (`return_not_faithful`).  Selection by verification is exactly blind to the
gauge, and the blindness is not vacuous. -/
theorem neutral_drift {Ω : Type*} {Q : ∀ ℓ, Y ℓ → Ω} (h : A.RespectsClosure Q)
    (g : A.Restructuring) (ℓ : L) (u : Y ℓ) :
    CEq (A.W ℓ) (g.act ℓ u) u ∧ Q ℓ (g.act ℓ u) = Q ℓ u :=
  ⟨g.act_ret ℓ u, A.capability_is_gauge h g ℓ u⟩

/-- **Evolutionary verification is exactly return measurement.**  A verdict is conserved by every
translation and blind to everything closure identifies — i.e. survives evolution — precisely when
it is a measurement of the verification return.  Nothing else is ever selected for. -/
theorem evolutionary_verification_is_exactly_return_measurement {Ω : Type*}
    (Q : ∀ ℓ, Y ℓ → Ω) :
    ((∀ (g : ℕ → L) (n : ℕ) (u : Y (g 0)), Q (g n) (A.evolve g n u) = Q (g 0) u) ∧
        A.RespectsClosure Q) ↔ A.MeasuredByReturn Q := by
  rw [← A.axiometric_verdict_characterisation]
  constructor
  · rintro ⟨hev, hresp⟩
    refine ⟨?_, hresp⟩
    intro ℓ m u
    have h := hev (fun n => if n = 0 then ℓ else m) 1 u
    rw [A.evolve_eq_direct] at h
    exact h
  · rintro ⟨hinv, hresp⟩
    exact ⟨fun g n u => A.verdict_conserved hinv g n u, hresp⟩

end TransFrame

/-! ## §7  Models: the framework is not vacuous -/

/-- The standard framework: occurrences are oriented identities, the reversal is the exchange of
the orientation, translation is the identity. -/
def standardFrame (L : Type u) (B₀ : Type v) :
    TransFrame L (fun _ => B₀) (fun _ => B₀ × Pole) where
  W := fun _ x => x.1
  E := fun _ p b => (b, p)
  recov := fun _ _ _ => rfl
  phi := fun _ _ b => b
  phi_id := fun _ _ => rfl
  phi_comp := fun _ _ _ _ => rfl
  T := fun _ _ u => u
  T_id := fun _ _ => rfl
  T_comp := fun _ _ _ _ => rfl
  T_ret := fun _ _ _ => rfl
  pi := fun _ _ => Equiv.refl Pole
  pi_id := fun _ => rfl
  pi_comp := fun _ _ _ _ => rfl
  T_ext := fun _ _ _ _ => rfl
  J := fun _ x => (x.1, Pole.other x.2)
  J_invol := by intro _ x; simp
  J_ret := fun _ _ => rfl
  J_ext := fun _ _ _ => rfl
  T_J := fun _ _ _ => rfl
  C := fun _ x => x
  C_idem := fun _ _ => rfl
  C_ret := fun _ _ => rfl
  T_C := fun _ _ _ => rfl

theorem standardFrame_separated (L : Type u) (B₀ : Type v) :
    (standardFrame L B₀).Separated := by
  intro ℓ b
  simp [standardFrame]

/-- The return of the standard framework is not injective: verification underdetermines the
occurrence. -/
theorem standardFrame_return_not_faithful (L : Type u) (B₀ : Type v) (ℓ : L) (b : B₀) :
    ∃ u v : B₀ × Pole, CEq ((standardFrame L B₀).W ℓ) u v ∧ u ≠ v :=
  (standardFrame L B₀).return_not_faithful (standardFrame_separated L B₀) ℓ b

/-- The exchange of the two poles as a permutation. -/
def otherPerm : Equiv.Perm Pole where
  toFun := Pole.other
  invFun := Pole.other
  left_inv := Pole.other_other
  right_inv := Pole.other_other

/-- A two-language framework whose translation genuinely *reverses* the orientation: the
relabelling `pi` is not a redundant field. -/
def flipFrame (B₀ : Type v) : TransFrame Bool (fun _ => B₀) (fun _ => B₀ × Pole) where
  W := fun _ x => x.1
  E := fun _ p b => (b, p)
  recov := fun _ _ _ => rfl
  phi := fun _ _ b => b
  phi_id := fun _ _ => rfl
  phi_comp := fun _ _ _ _ => rfl
  T := fun l m u => (u.1, if l = m then u.2 else Pole.other u.2)
  T_id := by intro l u; simp
  T_comp := by
    intro l m k u
    obtain ⟨b, p⟩ := u
    cases l <;> cases m <;> cases k <;> cases p <;> simp [Pole.other]
  T_ret := fun _ _ _ => rfl
  pi := fun l m => if l = m then Equiv.refl Pole else otherPerm
  pi_id := by intro l; simp
  pi_comp := by
    intro l m k p
    cases l <;> cases m <;> cases k <;> cases p <;> simp [otherPerm, Pole.other]
  T_ext := by
    intro l m p b
    by_cases h : l = m <;> simp [h, otherPerm]
  J := fun _ x => (x.1, Pole.other x.2)
  J_invol := by intro _ x; simp
  J_ret := fun _ _ => rfl
  J_ext := fun _ _ _ => rfl
  T_J := by
    intro l m u
    by_cases h : l = m <;> simp [h, Pole.other_other]
  C := fun _ x => x
  C_idem := fun _ _ => rfl
  C_ret := fun _ _ => rfl
  T_C := fun _ _ _ => rfl

/-- Translation between the two languages of `flipFrame` exchanges the poles: no language can
declare an absolute orientation. -/
theorem flip_pi_nontrivial (B₀ : Type v) :
    (flipFrame B₀).pi false true ≠ Equiv.refl Pole := by
  intro h
  have h2 := congrArg (fun e => e Pole.zero) h
  simp [flipFrame, otherPerm] at h2
  exact absurd h2 (Pole.other_ne Pole.zero)

theorem flipFrame_separated (B₀ : Type v) : (flipFrame B₀).Separated := by
  intro ℓ b
  simp [flipFrame]

/-- The smallest witness: one language, one relational identity, two occurrences that verification
cannot tell apart. -/
def witnessFrame : TransFrame Unit (fun _ => Unit) (fun _ => Pole) where
  W := fun _ _ => ()
  E := fun _ p _ => p
  recov := fun _ _ _ => rfl
  phi := fun _ _ b => b
  phi_id := fun _ _ => rfl
  phi_comp := fun _ _ _ _ => rfl
  T := fun _ _ u => u
  T_id := fun _ _ => rfl
  T_comp := fun _ _ _ _ => rfl
  T_ret := fun _ _ _ => rfl
  pi := fun _ _ => Equiv.refl Pole
  pi_id := fun _ => rfl
  pi_comp := fun _ _ _ _ => rfl
  T_ext := fun _ _ _ _ => rfl
  J := fun _ p => Pole.other p
  J_invol := by intro _ p; simp
  J_ret := fun _ _ => rfl
  J_ext := fun _ _ _ => rfl
  T_J := fun _ _ _ => rfl
  C := fun _ p => p
  C_idem := fun _ _ => rfl
  C_ret := fun _ _ => rfl
  T_C := fun _ _ _ => rfl

theorem witnessFrame_separated : witnessFrame.Separated := by
  intro ℓ b
  simp [witnessFrame]

/-- In the witness framework the polar reversal is a genuine change of occurrence which no verdict
of the language can register: the gauge is real and invisible at once. -/
theorem witness_gauge_real_and_invisible :
    witnessFrame.J () Pole.zero ≠ Pole.zero ∧
      CEq (witnessFrame.W ()) (witnessFrame.J () Pole.zero) Pole.zero :=
  ⟨by simp [witnessFrame, Pole.other], rfl⟩

/-! ## §8  The framework, bundled -/

/-- **The closure translational framework and its three consequences.**

For any separated framework `A`, any two languages `ℓ`, `m`, any programme `ms` of internal moves
and any verdict `Q`:

1. *(translation)* translation is invertible and every temporary origin cancels;
2. *(closure)* closure equality is preserved **and** reflected by translation, with no extra
   hypothesis, and the two orientations of an identity are closure-equal;
3. *(axiometry)* a verdict is language-independent and closure-respecting exactly when it is a
   measurement of the verification return;
4. *(ASI)* unbounded internal restructuring, and re-expression in another language, leave every
   such verdict exactly where it was — while the return is not faithful, so the invisible residue
   is real, and the only language-independent reading of it is a parity;
5. *(evolutionary verification)* an evolutionary history leaves no trace beyond its endpoints,
   verification verdicts are heritable in both directions, and the verdicts conserved by evolution
   are exactly the return measurements. -/
theorem closure_translational_framework
    {L : Type u} {B : L → Type v} {Y : L → Type w} (A : TransFrame L B Y)
    (hsep : A.Separated) (ℓ m : L) (b : B ℓ) (p : Pole) (ms : List TransFrame.Move)
    {Ω : Type*} (Q : ∀ ℓ, Y ℓ → Ω) :
    -- 1. translation
    (∀ u : Y ℓ, A.T m ℓ (A.T ℓ m u) = u) ∧
    (∀ (k : L) (u : Y ℓ), A.T m k (A.T ℓ m u) = A.T ℓ k u) ∧
    -- 2. closure
    (∀ u v : Y ℓ, CEq (A.W ℓ) u v ↔ CEq (A.W m) (A.T ℓ m u) (A.T ℓ m v)) ∧
    (∀ q : Pole, CEq (A.W ℓ) (A.E ℓ p b) (A.E ℓ q b)) ∧
    -- 3. axiometry
    ((A.Invariant Q ∧ A.RespectsClosure Q) ↔ A.MeasuredByReturn Q) ∧
    -- 4. ASI
    (A.RespectsClosure Q → ∀ u : Y ℓ, Q ℓ (A.run ℓ ms u) = Q ℓ u) ∧
    (A.Invariant Q → A.RespectsClosure Q → ∀ u : Y ℓ,
      A.T m ℓ (A.run m ms (A.T ℓ m u)) = A.run ℓ ms u ∧
        Q m (A.run m ms (A.T ℓ m u)) = Q ℓ u) ∧
    (∃ u v : Y ℓ, CEq (A.W ℓ) u v ∧ u ≠ v) ∧
    (∀ i k : ℕ, (A.walk ℓ (A.E ℓ p b) (i + k) = A.walk ℓ (A.E ℓ p b) i ↔ Even k)) ∧
    -- 5. evolutionary verification
    (∀ (ks ks' : List L) (u : Y ℓ), A.route ℓ ks m u = A.route ℓ ks' m u) ∧
    (∀ (g : ℕ → L) (n : ℕ) (u v : Y (g 0)),
      CEq (A.W (g 0)) u v ↔ CEq (A.W (g n)) (A.evolve g n u) (A.evolve g n v)) ∧
    (((∀ (g : ℕ → L) (n : ℕ) (u : Y (g 0)), Q (g n) (A.evolve g n u) = Q (g 0) u) ∧
        A.RespectsClosure Q) ↔ A.MeasuredByReturn Q) :=
  ⟨fun u => A.T_T ℓ m u,
   fun k u => A.T_comp ℓ m k u,
   fun u v => A.ceq_iff ℓ m u v,
   fun q => A.poles_closure_equal ℓ p q b,
   A.axiometric_verdict_characterisation Q,
   fun hresp u => A.self_improvement_preserves_verdicts hresp ℓ ms u,
   fun hinv hresp u => A.reexpression_preserves_verdicts hinv hresp ℓ m ms u,
   A.return_not_faithful hsep ℓ b,
   fun i k => A.walk_eq_iff_even hsep ℓ p b i k,
   fun ks ks' u => A.history_independence ℓ m ks ks' u,
   fun g n u v => A.verification_heritable g n u v,
   A.evolutionary_verification_is_exactly_return_measurement Q⟩

end NRRF627

#print axioms NRRF627.TransFrame.ceq_iff
#print axioms NRRF627.TransFrame.axiometric_verdict_characterisation
#print axioms NRRF627.TransFrame.capability_is_gauge
#print axioms NRRF627.TransFrame.reexpression_preserves_verdicts
#print axioms NRRF627.TransFrame.residue_is_parity
#print axioms NRRF627.TransFrame.route_eq_direct
#print axioms NRRF627.TransFrame.verification_heritable
#print axioms NRRF627.TransFrame.evolutionary_verification_is_exactly_return_measurement
#print axioms NRRF627.flip_pi_nontrivial
#print axioms NRRF627.closure_translational_framework
