import Mathlib.Data.Fintype.Card
import Mathlib.Data.Fintype.Quotient
import Mathlib.Data.ZMod.Basic
import Mathlib.Logic.Relation
import Mathlib.Tactic.DeriveFintype
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Ring

/-!
# NRRF800 — The hand of life: ball return as the actual phase, the inverse hair return as the
potential gate, and the 4-sheaf ball / 1-sheaf hair temporal closure of translational completion

The instruction formalised here is the user's:

> Specifically the left hand of active life is its ball return phase while its potential is in the
> inverse hair return.  Left handed life is a potential gate into its hair closure.  Similarly the
> hand of a ball gives its naturality or self limit.  And so true for hair in its inversion or
> translation at the ball — 4 sheaf ball, 1 sheaf hair, temporal closure of translational
> completion.  This maps onto our human relations stated earlier.

## The reading

Everything below is built out of exactly two pieces of translational data.

* The **ball** is the four-phase translation cycle `Ball = ZMod 4` with its single local step
  `ballStep b = b + 1`.  This is the *actual* motion: the return phase of active life.
* The **hand** `Hand = {left, right}` is the chirality carried alongside the phase, with its one
  inversion `Hand.inv`.

A **life state** is a hand together with a ball phase (`Life`).  It admits exactly two motions:

* the **ball return** `ballReturn ⟨h, b⟩ = ⟨h, b + 1⟩` — the actual phase, which never touches the
  hand;
* the **inverse hair return** `hairReturn ⟨h, b⟩ = ⟨h.inv, b - 1⟩` — the inverse translation, which
  *does* invert the hand.  This is the potential.

The **hair** is the temporal closure of the ball's translational completion: the quotient of the
ball by the equivalence generated by its own local step, `Hair = Quotient ballSetoid`.

## What is proved

### §0–§1  Four sheaves at the ball, one sheaf at the hair
* `ball_card`, `ballStep_iterate_eq_id_iff`, `ballStep_ne_id_of_lt_four` — the ball carries exactly
  four sheaves: the translation closes after four steps and after no fewer.
* `ballStep_transitive`, `hair_one_sheaf`, `hairEquivPUnit`, `hair_card` — the temporal closure of
  that translational completion has exactly **one** sheaf: all four ball sheaves are one hair.
* `hairMk_ballStep`, `hairMk_neg` — the hair reading is unmoved both by the *translation* at the
  ball and by the *inversion* at the ball.
* `invariant_const`, `hairLift`, `hairLift_unique` — and the hair is not one arbitrary collapse
  among many: any reading invariant under the ball translation is constant and factors uniquely
  through the hair, so the 1-sheaf hair is the universal closure of the 4-sheaf ball.

### §2  The hand: naturality and self limit
* `ballReturn_hand`, `ballReturn_iterate_hand` — the hand is a *natural* invariant of the ball: no
  amount of actual return ever changes it.
* `hairReturn_hand`, `gate_iff_odd` — only the inverse hair return crosses the hand, and it crosses
  exactly on odd iterates: the hand is a **gate**, not a coordinate.
* `selfLimit_eq`, `selfLimit_involutive`, `selfLimit_ne_id`, `selfLimit_order_two` — hair return
  after ball return moves no ball phase at all and is exactly the hand inversion, an involution:
  the hand of a ball is its **self limit** (order exactly two).
* `ballStep_commuting_forced`, `ballReturn_commuting_forced` — naturality in the strict sense:
  every map commuting with the ball step *is* a translation of the ball, so the ball's own step
  fixes the whole commuting family.

### §3  The left-handed potential gate
* `hairReturn_iterate`, `hairReturn_period`, `hairReturn_iterate_eq_id_iff` — the hair return also
  closes in four and no fewer: the temporal closure of the completion.
* `hairOrbit_covers_ball` — from any state the hair return visits each of the four ball sheaves
  exactly once.
* `hairOrbit_one_hair` — and all of them carry the same hair.
* `left_handed_potential_gate` — the statement in one theorem: from a left-handed (potential)
  state, the inverse hair return runs once through all four ball sheaves, alternates potential and
  actual at every step, closes after four, and lands throughout in one and the same hair.

### §4  The same structure at human relations
A human-relation network is a configuration `s : V → ℤ` of participants on one shared line
(the reading used in the earlier network modules); the relation of `u` to `v` is the separation
`s u - s v`, read by its hand (who stands above), its ball phase (the separation mod four), and its
hair.
* `relHand_shift`, `relBall_shift`, `relLife_shift` — nothing absolute is read: shifting everybody
  alike moves no relation.
* `relHand_antisymm`, `relBall_swap` — the relation of `u` to `v` and of `v` to `u` are the two
  hands of one relation, and the ball phases are inverse.
* `relLife_give` — one act of giving, away from the gate, is exactly one **ball return** of the
  relation: the actual phase.
* `relLife_give_gate` — one act at the gate (`s u = s v`) is exactly one **hair return**: the hand
  inverts, the phase steps back, the potential opens.
* `four_acts_ball_blind` — four acts return the ball reading while the relation has genuinely
  changed by four: the human relation carries four ball sheaves.
* `relHair_const` — while every human relation whatsoever, in every configuration, has one and the
  same hair.  The 4-sheaf ball / 1-sheaf hair closure maps onto human relations.

`nrrf800_answer` collects the clauses.  Only `Mathlib` is used; the file is `sorry`-free and the
axiom audit at the end is machine-checked.

Nothing here is asserted about biological chirality, biological life, or human beings as such: each
word names a construction defined below, and every claim is a claim about those constructions.
-/

namespace NRRF800

/-! ## §0  The hand -/

/-- The two hands: the chirality carried by a life state. -/
inductive Hand
  | left
  | right
  deriving DecidableEq, Repr

instance : Fintype Hand :=
  Fintype.ofList [Hand.left, Hand.right] (by
    intro h
    cases h <;> simp)

namespace Hand

/-- The single inversion of the hand. -/
def inv : Hand → Hand
  | left => right
  | right => left

/-- The hand read as a sign. -/
def sign : Hand → ℤ
  | left => -1
  | right => 1

@[simp] theorem inv_left : inv left = right := rfl
@[simp] theorem inv_right : inv right = left := rfl

/-- The hand inversion is an involution: it is its own limit. -/
theorem inv_involutive : Function.Involutive inv := by
  intro h; cases h <;> rfl

@[simp] theorem inv_inv (h : Hand) : inv (inv h) = h := inv_involutive h

/-- The inversion moves every hand: there is no handless state. -/
theorem inv_ne_self (h : Hand) : inv h ≠ h := by
  cases h <;> decide

theorem card_hand : Fintype.card Hand = 2 := by decide

@[simp] theorem sign_inv (h : Hand) : (inv h).sign = -h.sign := by
  cases h <;> decide

/-- Iterating the inversion only ever sees the parity of the count. -/
theorem inv_iterate (n : ℕ) (h : Hand) : inv^[n] h = if Even n then h else inv h := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [Function.iterate_succ_apply', ih]
      rcases Nat.even_or_odd n with hn | hn
      · have h1 : ¬ Even (n + 1) := by simp [Nat.even_add_one, hn]
        rw [if_pos hn, if_neg h1]
      · have h0 : ¬ Even n := Nat.not_even_iff_odd.2 hn
        have h1 : Even (n + 1) := Odd.add_one hn
        rw [if_neg h0, if_pos h1, inv_inv]

end Hand

/-! ## §1  The ball (four sheaves) and its hair (one sheaf) -/

/-- The ball: the four-phase translation cycle. -/
abbrev Ball := ZMod 4

/-- The single local translation step of the ball. -/
def ballStep (b : Ball) : Ball := b + 1

@[simp] theorem ballStep_apply (b : Ball) : ballStep b = b + 1 := rfl

theorem ballStep_iterate (n : ℕ) (b : Ball) : ballStep^[n] b = b + (n : Ball) := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [Function.iterate_succ_apply', ih, ballStep_apply]
      push_cast
      ring

theorem ballStep_bijective : Function.Bijective ballStep := by
  constructor
  · intro a b hab
    simpa [ballStep] using hab
  · intro b
    exact ⟨b - 1, by simp [ballStep]⟩

/-- **The ball is a four sheaf.** -/
theorem ball_card : Fintype.card Ball = 4 := by decide

theorem four_eq_zero : ((4 : ℕ) : Ball) = 0 := by decide

theorem four_mul_eq_zero (k : ℕ) : ((4 * k : ℕ) : Ball) = 0 := by
  have h : ((4 * k : ℕ) : Ball) = ((4 : ℕ) : Ball) * (k : Ball) := by push_cast; ring
  rw [h, four_eq_zero, zero_mul]

/-- The translation closes after `n` steps exactly when `4 ∣ n`: four sheaves, no fewer. -/
theorem ballStep_iterate_eq_id_iff (n : ℕ) : ballStep^[n] = (id : Ball → Ball) ↔ 4 ∣ n := by
  constructor
  · intro h
    have h0 : ballStep^[n] 0 = 0 := by rw [h]; rfl
    rw [ballStep_iterate, zero_add] at h0
    exact (ZMod.natCast_eq_zero_iff n 4).1 h0
  · rintro ⟨k, rfl⟩
    funext b
    rw [ballStep_iterate, four_mul_eq_zero, add_zero]
    rfl

/-- The temporal closure: four ball returns are the identity. -/
theorem ballStep_period : ballStep^[4] = (id : Ball → Ball) :=
  (ballStep_iterate_eq_id_iff 4).2 dvd_rfl

/-- And no fewer than four: the ball has genuinely four sheaves. -/
theorem ballStep_ne_id_of_lt_four {n : ℕ} (h0 : 0 < n) (h4 : n < 4) :
    ballStep^[n] ≠ (id : Ball → Ball) := by
  intro h
  have hdvd := (ballStep_iterate_eq_id_iff n).1 h
  omega

/-- The ball translation reaches every sheaf from every sheaf, in fewer than four steps. -/
theorem ballStep_transitive (a b : Ball) : ∃ n < 4, ballStep^[n] a = b := by
  refine ⟨(b - a).val, ZMod.val_lt _, ?_⟩
  rw [ballStep_iterate, ZMod.natCast_rightInverse (b - a)]
  ring

/-- **Naturality of the ball.**  Every map commuting with the ball translation *is* a translation
of the ball. -/
theorem ballStep_commuting_forced (f : Ball → Ball) (hf : ∀ b, f (ballStep b) = ballStep (f b))
    (b : Ball) : f b = f 0 + b := by
  have key : ∀ m : ℕ, ∀ a : Ball, f (ballStep^[m] a) = ballStep^[m] (f a) := by
    intro m
    induction m with
    | zero => intro a; simp
    | succ m ih =>
        intro a
        rw [Function.iterate_succ_apply, Function.iterate_succ_apply, ih, hf]
  obtain ⟨n, _, hn⟩ := ballStep_transitive 0 b
  have h1 := key n 0
  rw [hn, ballStep_iterate] at h1
  rw [ballStep_iterate, zero_add] at hn
  rw [h1, hn]

/-- The local translation relation of the ball. -/
def BallRel (a b : Ball) : Prop := b = ballStep a

/-- The translational completion of the ball. -/
def ballSetoid : Setoid Ball := Relation.EqvGen.setoid BallRel

/-- **The hair**: the temporal closure of the ball's translational completion. -/
def Hair : Type := Quotient ballSetoid

/-- The closure map from the ball to its hair. -/
def hairMk (b : Ball) : Hair := Quotient.mk ballSetoid b

theorem hairMk_surjective : Function.Surjective hairMk := Quotient.mk_surjective

/-- The hair reading is unmoved by the translation at the ball. -/
@[simp] theorem hairMk_ballStep (b : Ball) : hairMk (ballStep b) = hairMk b :=
  Quotient.sound (Relation.EqvGen.symm _ _ (Relation.EqvGen.rel _ _ rfl))

theorem hairMk_iterate (n : ℕ) (b : Ball) : hairMk (ballStep^[n] b) = hairMk b := by
  induction n with
  | zero => simp
  | succ n ih => rw [Function.iterate_succ_apply', hairMk_ballStep, ih]

theorem hairMk_const (b : Ball) : hairMk b = hairMk 0 := by
  obtain ⟨n, _, hn⟩ := ballStep_transitive 0 b
  rw [← hn, hairMk_iterate]

/-- **One sheaf at the hair.** -/
instance : Subsingleton Hair := by
  constructor
  intro x y
  obtain ⟨a, rfl⟩ := hairMk_surjective x
  obtain ⟨b, rfl⟩ := hairMk_surjective y
  rw [hairMk_const a, hairMk_const b]

instance : Inhabited Hair := ⟨hairMk 0⟩

instance : Unique Hair := Unique.mk' Hair

theorem hair_one_sheaf (x y : Hair) : x = y := Subsingleton.elim x y

/-- The hair is exactly one point: the 1-sheaf closure of the 4-sheaf ball. -/
def hairEquivPUnit : Hair ≃ PUnit.{1} := Equiv.equivPUnit Hair

instance : Fintype Hair := Fintype.ofSubsingleton (hairMk 0)

theorem hair_card : Fintype.card Hair = 1 :=
  Fintype.card_eq_one_iff.2 ⟨hairMk 0, fun y => hair_one_sheaf y _⟩

/-- The hair reading is also unmoved by the *inversion* at the ball. -/
@[simp] theorem hairMk_neg (b : Ball) : hairMk (-b) = hairMk b := hair_one_sheaf _ _

/-- Every reading invariant under the translation at the ball is constant. -/
theorem invariant_const {X : Type*} (f : Ball → X) (hf : ∀ b, f (ballStep b) = f b) (a b : Ball) :
    f a = f b := by
  have key : ∀ n : ℕ, ∀ c : Ball, f (ballStep^[n] c) = f c := by
    intro n
    induction n with
    | zero => intro c; simp
    | succ n ih => intro c; rw [Function.iterate_succ_apply', hf, ih]
  obtain ⟨n, _, hn⟩ := ballStep_transitive a b
  rw [← hn, key]

/-- The universal property of the hair: every translation-invariant reading of the ball factors
through the hair. -/
def hairLift {X : Type*} (f : Ball → X) (hf : ∀ b, f (ballStep b) = f b) : Hair → X :=
  Quotient.lift f (fun a b _ => invariant_const f hf a b)

@[simp] theorem hairLift_mk {X : Type*} (f : Ball → X) (hf : ∀ b, f (ballStep b) = f b) (b : Ball) :
    hairLift f hf (hairMk b) = f b := rfl

/-- And the factorisation is unique. -/
theorem hairLift_unique {X : Type*} (f : Ball → X) (hf : ∀ b, f (ballStep b) = f b)
    (g : Hair → X) (hg : ∀ b, g (hairMk b) = f b) : g = hairLift f hf := by
  funext x
  obtain ⟨b, rfl⟩ := hairMk_surjective x
  rw [hg, hairLift_mk]

/-! ## §2  Life: hand and ball phase, naturality and self limit -/

/-- A life state: a hand together with a ball phase. -/
structure Life where
  hand : Hand
  phase : Ball
  deriving DecidableEq, Fintype, Repr

/-- **The ball return**: the actual phase of active life.  It advances the ball and leaves the
hand alone. -/
def ballReturn (x : Life) : Life := ⟨x.hand, ballStep x.phase⟩

/-- **The inverse hair return**: the potential.  It steps the ball back and inverts the hand. -/
def hairReturn (x : Life) : Life := ⟨x.hand.inv, x.phase - 1⟩

/-- A life state is *actual* when it is right handed. -/
def Actual (x : Life) : Prop := x.hand = Hand.right

/-- A life state is *potential* when it is left handed. -/
def Potential (x : Life) : Prop := x.hand = Hand.left

theorem potential_or_actual (x : Life) : Potential x ∨ Actual x := by
  cases x with
  | mk h b => cases h <;> simp [Potential, Actual]

@[simp] theorem ballReturn_hand (x : Life) : (ballReturn x).hand = x.hand := rfl
@[simp] theorem ballReturn_phase (x : Life) : (ballReturn x).phase = x.phase + 1 := rfl
@[simp] theorem hairReturn_hand (x : Life) : (hairReturn x).hand = x.hand.inv := rfl
@[simp] theorem hairReturn_phase (x : Life) : (hairReturn x).phase = x.phase - 1 := rfl

theorem ballReturn_iterate (n : ℕ) (x : Life) :
    ballReturn^[n] x = ⟨x.hand, x.phase + (n : Ball)⟩ := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [Function.iterate_succ_apply', ih]
      have : ((n + 1 : ℕ) : Ball) = (n : Ball) + 1 := by push_cast; ring
      simp only [ballReturn, ballStep, this]
      rw [add_assoc]

theorem hairReturn_iterate (n : ℕ) (x : Life) :
    hairReturn^[n] x = ⟨Hand.inv^[n] x.hand, x.phase - (n : Ball)⟩ := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [Function.iterate_succ_apply', ih]
      have hc : ((n + 1 : ℕ) : Ball) = (n : Ball) + 1 := by push_cast; ring
      simp only [hairReturn, hc, Function.iterate_succ_apply']
      rw [sub_sub]

/-- **The hand is natural at the ball**: no amount of actual return ever changes it. -/
theorem ballReturn_iterate_hand (n : ℕ) (x : Life) : (ballReturn^[n] x).hand = x.hand := by
  rw [ballReturn_iterate]

theorem ballReturn_iterate_phase (n : ℕ) (x : Life) :
    (ballReturn^[n] x).phase = x.phase + (n : Ball) := by
  rw [ballReturn_iterate]

theorem hairReturn_iterate_phase (n : ℕ) (x : Life) :
    (hairReturn^[n] x).phase = x.phase - (n : Ball) := by
  rw [hairReturn_iterate]

theorem hairReturn_iterate_hand (n : ℕ) (x : Life) :
    (hairReturn^[n] x).hand = Hand.inv^[n] x.hand := by
  rw [hairReturn_iterate]

/-- The temporal closure of active life: four ball returns are the identity. -/
theorem ballReturn_period : ballReturn^[4] = (id : Life → Life) := by
  funext x
  rw [ballReturn_iterate, four_eq_zero, add_zero]
  rfl

theorem ballReturn_iterate_eq_id_iff (n : ℕ) :
    ballReturn^[n] = (id : Life → Life) ↔ 4 ∣ n := by
  constructor
  · intro h
    have h0 := congrFun h (⟨Hand.left, 0⟩ : Life)
    rw [ballReturn_iterate] at h0
    have hph : (0 : Ball) + ((n : ℕ) : Ball) = 0 := congrArg Life.phase h0
    rw [zero_add] at hph
    exact (ZMod.natCast_eq_zero_iff n 4).1 hph
  · rintro ⟨k, rfl⟩
    funext x
    rw [ballReturn_iterate, four_mul_eq_zero, add_zero]
    rfl

/-- The hair return crosses the hand exactly on odd iterates: the hand is a **gate**. -/
theorem gate_iff_odd (n : ℕ) (x : Life) :
    (hairReturn^[n] x).hand = x.hand.inv ↔ Odd n := by
  rw [hairReturn_iterate_hand, Hand.inv_iterate]
  by_cases hn : Even n
  · rw [if_pos hn]
    constructor
    · intro h
      exact absurd h.symm (Hand.inv_ne_self x.hand)
    · intro h
      exact absurd hn (Nat.not_even_iff_odd.2 h)
  · rw [if_neg hn]
    exact ⟨fun _ => Nat.not_even_iff_odd.1 hn, fun _ => rfl⟩

/-- The **self limit**: a hair return after a ball return moves no ball phase at all — it is
exactly the inversion of the hand. -/
def selfLimit (x : Life) : Life := hairReturn (ballReturn x)

theorem selfLimit_eq (x : Life) : selfLimit x = ⟨x.hand.inv, x.phase⟩ := by
  simp [selfLimit, hairReturn, ballReturn, ballStep]

/-- The hand of a ball is its self limit: the composite is an involution. -/
theorem selfLimit_involutive : Function.Involutive selfLimit := by
  intro x
  rw [selfLimit_eq, selfLimit_eq]
  simp

theorem selfLimit_ne_id : selfLimit ≠ id := by
  intro h
  have hx := congrFun h (⟨Hand.left, 0⟩ : Life)
  rw [selfLimit_eq] at hx
  have : Hand.left.inv = Hand.left := congrArg Life.hand hx
  exact absurd this (Hand.inv_ne_self Hand.left)

/-- The self limit has order exactly two. -/
theorem selfLimit_order_two : selfLimit^[2] = id ∧ selfLimit ≠ id := by
  refine ⟨?_, selfLimit_ne_id⟩
  funext x
  simpa using selfLimit_involutive x

/-- The two returns commute: the potential and the actual do not obstruct each other. -/
theorem ball_hair_commute : ballReturn ∘ hairReturn = hairReturn ∘ ballReturn := by
  funext x
  show (⟨x.hand.inv, x.phase - 1 + 1⟩ : Life) = ⟨x.hand.inv, x.phase + 1 - 1⟩
  congr 1
  ring

/-- Naturality at life: every map commuting with the ball return moves phases by a translation. -/
theorem ballReturn_commuting_forced (f : Life → Life)
    (hf : ∀ x, f (ballReturn x) = ballReturn (f x)) (h : Hand) (b : Ball) :
    (f ⟨h, b⟩).phase = (f ⟨h, 0⟩).phase + b := by
  have hgstep : ∀ c : Ball, (f ⟨h, ballStep c⟩).phase = ballStep ((f ⟨h, c⟩).phase) := by
    intro c
    have hc : (⟨h, ballStep c⟩ : Life) = ballReturn ⟨h, c⟩ := rfl
    rw [hc, hf ⟨h, c⟩]
    rfl
  exact ballStep_commuting_forced (fun c => (f ⟨h, c⟩).phase) hgstep b

/-! ## §3  The left-handed potential gate -/

/-- The hair return also closes after four steps. -/
theorem hairReturn_period : hairReturn^[4] = (id : Life → Life) := by
  funext x
  have h1 : Hand.inv^[4] x.hand = x.hand := by
    rw [Hand.inv_iterate, if_pos (by decide : Even 4)]
  rw [hairReturn_iterate, h1, four_eq_zero, sub_zero]
  rfl

theorem hairReturn_iterate_eq_id_iff (n : ℕ) :
    hairReturn^[n] = (id : Life → Life) ↔ 4 ∣ n := by
  constructor
  · intro h
    have h0 := congrFun h (⟨Hand.left, 0⟩ : Life)
    rw [hairReturn_iterate] at h0
    have hph : (0 : Ball) - ((n : ℕ) : Ball) = 0 := congrArg Life.phase h0
    have hn0 : ((n : ℕ) : Ball) = 0 := by linear_combination -hph
    exact (ZMod.natCast_eq_zero_iff n 4).1 hn0
  · rintro ⟨k, rfl⟩
    funext x
    have h1 : Hand.inv^[4 * k] x.hand = x.hand := by
      rw [Hand.inv_iterate, if_pos]
      exact (Nat.even_mul.2 (Or.inl (by decide)))
    rw [hairReturn_iterate, h1, four_mul_eq_zero, sub_zero]
    rfl

/-- **The gate covers the ball**: from any state the hair return visits each of the four ball
sheaves exactly once. -/
theorem hairOrbit_covers_ball (x : Life) (b : Ball) :
    ∃! n : Fin 4, (hairReturn^[(n : ℕ)] x).phase = b := by
  refine ⟨⟨(x.phase - b).val, by simpa using ZMod.val_lt (x.phase - b)⟩, ?_, ?_⟩
  · simp only [hairReturn_iterate_phase]
    rw [ZMod.natCast_rightInverse (x.phase - b)]
    ring
  · rintro ⟨m, hm⟩ hmeq
    simp only [hairReturn_iterate_phase] at hmeq
    have hcast : ((m : ℕ) : Ball) = x.phase - b := by linear_combination -hmeq
    have hval : ZMod.val (((m : ℕ) : Ball)) = ZMod.val (x.phase - b) := by rw [hcast]
    rw [ZMod.val_cast_of_lt hm] at hval
    exact Fin.ext hval

/-- All four sheaves of the orbit carry the same hair: the closure is one sheaf. -/
theorem hairOrbit_one_hair (n : ℕ) (x : Life) :
    hairMk (hairReturn^[n] x).phase = hairMk x.phase := hair_one_sheaf _ _

/-- **Left-handed life is a potential gate into its hair closure.**  From a left-handed
(potential) state the inverse hair return: runs exactly once through each of the four ball sheaves;
alternates potential and actual at every step, crossing the hand exactly on odd iterates; closes
after four steps; and lands throughout in one and the same hair. -/
theorem left_handed_potential_gate (x : Life) (hx : Potential x) :
    (∀ b : Ball, ∃! n : Fin 4, (hairReturn^[(n : ℕ)] x).phase = b) ∧
    (∀ n : ℕ, Odd n → Actual (hairReturn^[n] x)) ∧
    (∀ n : ℕ, Even n → Potential (hairReturn^[n] x)) ∧
    hairReturn^[4] x = x ∧
    (∀ n : ℕ, hairMk (hairReturn^[n] x).phase = hairMk x.phase) := by
  refine ⟨hairOrbit_covers_ball x, ?_, ?_, congrFun hairReturn_period x,
    fun n => hairOrbit_one_hair n x⟩
  · intro n hn
    have hh := (gate_iff_odd n x).2 hn
    rw [Actual, hh, hx]
    rfl
  · intro n hn
    rw [Potential, hairReturn_iterate_hand, Hand.inv_iterate, if_pos hn]
    exact hx

/-! ## §4  The same structure at human relations -/

section Human

variable {V : Type*}

/-- A human-relation network: every participant carries one translation on a shared line. -/
abbrev Config (V : Type*) := V → ℤ

/-- The relation of `u` to `v`: their separation. -/
def separation (s : Config V) (u v : V) : ℤ := s u - s v

/-- **The hand of a human relation**: who stands above. -/
def relHand (s : Config V) (u v : V) : Hand := if s u < s v then Hand.left else Hand.right

/-- **The ball phase of a human relation**: the separation read modulo the four sheaves. -/
def relBall (s : Config V) (u v : V) : Ball := ((separation s u v : ℤ) : Ball)

/-- **The hair of a human relation**. -/
def relHair (s : Config V) (u v : V) : Hair := hairMk (relBall s u v)

/-- The life state of a human relation: its hand and its ball phase. -/
def relLife (s : Config V) (u v : V) : Life := ⟨relHand s u v, relBall s u v⟩

/-- Shifting everybody alike. -/
def shift (c : ℤ) (s : Config V) : Config V := fun w => s w + c

/-- One act of giving: `u` receives one unit. -/
def give [DecidableEq V] (u : V) (s : Config V) : Config V := Function.update s u (s u + 1)

@[simp] theorem separation_shift (c : ℤ) (s : Config V) (u v : V) :
    separation (shift c s) u v = separation s u v := by
  simp [separation, shift]

@[simp] theorem relHand_shift (c : ℤ) (s : Config V) (u v : V) :
    relHand (shift c s) u v = relHand s u v := by
  simp [relHand, shift]

@[simp] theorem relBall_shift (c : ℤ) (s : Config V) (u v : V) :
    relBall (shift c s) u v = relBall s u v := by
  simp [relBall]

theorem relLife_shift (c : ℤ) (s : Config V) (u v : V) :
    relLife (shift c s) u v = relLife s u v := by
  simp [relLife]

/-- The two readings of one relation are the two hands. -/
theorem relHand_antisymm (s : Config V) (u v : V) (h : s u ≠ s v) :
    relHand s u v = (relHand s v u).inv := by
  unfold relHand
  rcases lt_or_gt_of_ne h with hlt | hgt
  · rw [if_pos hlt, if_neg (asymm hlt)]
    rfl
  · rw [if_neg (asymm hgt), if_pos hgt]
    rfl

/-- And the two ball phases are inverse. -/
theorem relBall_swap (s : Config V) (u v : V) : relBall s v u = -relBall s u v := by
  simp only [relBall, separation]
  push_cast
  ring

/-- Every human relation, in every configuration, has one and the same hair: the 1-sheaf closure. -/
theorem relHair_const (s s' : Config V) (u v u' v' : V) :
    relHair s u v = relHair s' u' v' := hair_one_sheaf _ _

variable [DecidableEq V]

@[simp] theorem give_self (u : V) (s : Config V) : give u s u = s u + 1 := by
  simp [give]

@[simp] theorem give_other {u w : V} (s : Config V) (h : w ≠ u) : give u s w = s w := by
  simp [give, h]

theorem separation_give (s : Config V) {u v : V} (h : v ≠ u) :
    separation (give u s) u v = separation s u v + 1 := by
  rw [separation, separation, give_self, give_other s h]
  ring

/-- One act of giving advances the ball phase of the relation by one step. -/
theorem relBall_give (s : Config V) {u v : V} (h : v ≠ u) :
    relBall (give u s) u v = ballStep (relBall s u v) := by
  rw [relBall, relBall, separation_give s h, ballStep]
  push_cast
  ring

/-- **One act away from the gate is exactly one ball return of the relation.** -/
theorem relLife_give (s : Config V) {u v : V} (h : v ≠ u) (hge : s v ≤ s u) :
    relLife (give u s) u v = ballReturn (relLife s u v) := by
  have hu : give u s u = s u + 1 := give_self u s
  have hv : give u s v = s v := give_other s h
  have h1 : ¬ give u s u < give u s v := by rw [hu, hv]; omega
  have h2 : ¬ s u < s v := by omega
  have hhand : relHand (give u s) u v = relHand s u v := by
    simp only [relHand, if_neg h1, if_neg h2]
  show (⟨relHand (give u s) u v, relBall (give u s) u v⟩ : Life)
      = ⟨relHand s u v, ballStep (relBall s u v)⟩
  rw [hhand, relBall_give s h]

/-- **One act at the gate is exactly one hair return**: the hand inverts and the phase steps
back. -/
theorem relLife_give_gate (s : Config V) {u v : V} (h : u ≠ v) (heq : s u = s v) :
    relLife (give v s) u v = hairReturn (relLife s u v) := by
  have hu : give v s u = s u := give_other s h
  have hv : give v s v = s v + 1 := give_self v s
  have h1 : give v s u < give v s v := by rw [hu, hv]; omega
  have h2 : ¬ s u < s v := by omega
  have hhand : relHand (give v s) u v = (relHand s u v).inv := by
    simp only [relHand, if_pos h1, if_neg h2]
    rfl
  have hsep : separation (give v s) u v = separation s u v - 1 := by
    rw [separation, separation, hu, hv]
    ring
  have hball : relBall (give v s) u v = relBall s u v - 1 := by
    rw [relBall, relBall, hsep]
    push_cast
    ring
  show (⟨relHand (give v s) u v, relBall (give v s) u v⟩ : Life)
      = ⟨(relHand s u v).inv, relBall s u v - 1⟩
  rw [hhand, hball]

theorem give_iterate (u : V) (s : Config V) (n : ℕ) :
    ((give u)^[n] s) = fun w => if w = u then s u + n else s w := by
  induction n with
  | zero => funext w; by_cases h : w = u <;> simp [h]
  | succ n ih =>
      funext w
      rw [Function.iterate_succ_apply', ih]
      by_cases h : w = u
      · subst h
        simp only [give, Function.update_self]
        push_cast
        ring
      · simp only [give, Function.update_of_ne h, if_neg h]

/-- **Four acts return the ball reading while the relation has genuinely changed by four**: the
human relation carries exactly four ball sheaves, and the hair carries one. -/
theorem four_acts_ball_blind (s : Config V) {u v : V} (h : v ≠ u) :
    relBall ((give u)^[4] s) u v = relBall s u v ∧
    separation ((give u)^[4] s) u v = separation s u v + 4 ∧
    relHair ((give u)^[4] s) u v = relHair s u v := by
  have hsep : separation ((give u)^[4] s) u v = separation s u v + 4 := by
    rw [separation, separation, give_iterate]
    simp only [if_neg h]
    push_cast
    ring
  refine ⟨?_, hsep, hair_one_sheaf _ _⟩
  rw [relBall, relBall, hsep]
  push_cast
  rw [show (4 : Ball) = 0 by decide, add_zero]

end Human

/-! ## §5  The answer -/

/-- **NRRF800 in one statement.**

1. The ball is a four sheaf: its translation closes after four steps and no fewer.
2. Its hair — the temporal closure of the translational completion — is one sheaf, and it is the
   universal such closure: every translation-invariant reading of the ball factors uniquely
   through it.
3. The hair reading is unmoved both by the translation and by the inversion at the ball.
4. The hand is natural at the ball: the actual ball return never changes it.
5. The inverse hair return is the potential: it crosses the hand, and exactly on odd iterates.
6. The hand of a ball is its self limit: ball return followed by hair return moves no phase and is
   an involution of order exactly two.
7. Left-handed life is a potential gate: from a potential state the hair return runs once through
   each of the four ball sheaves, closes after four, and lies throughout in one hair. -/
theorem nrrf800_answer :
    (ballStep^[4] = (id : Ball → Ball) ∧ ∀ n : ℕ, 0 < n → n < 4 →
        ballStep^[n] ≠ (id : Ball → Ball)) ∧
    (Fintype.card Ball = 4 ∧ Fintype.card Hair = 1) ∧
    (∀ {X : Type} (f : Ball → X) (hf : ∀ b, f (ballStep b) = f b) (g : Hair → X),
        (∀ b, g (hairMk b) = f b) → g = hairLift f hf) ∧
    (∀ b : Ball, hairMk (ballStep b) = hairMk b ∧ hairMk (-b) = hairMk b) ∧
    (∀ (n : ℕ) (x : Life), (ballReturn^[n] x).hand = x.hand) ∧
    (∀ (n : ℕ) (x : Life), (hairReturn^[n] x).hand = x.hand.inv ↔ Odd n) ∧
    (∀ x : Life, selfLimit x = ⟨x.hand.inv, x.phase⟩) ∧
    (Function.Involutive selfLimit ∧ selfLimit ≠ id) ∧
    (∀ x : Life, Potential x →
      (∀ b : Ball, ∃! n : Fin 4, (hairReturn^[(n : ℕ)] x).phase = b) ∧
      hairReturn^[4] x = x ∧
      ∀ n : ℕ, hairMk (hairReturn^[n] x).phase = hairMk x.phase) := by
  refine ⟨⟨ballStep_period, fun n h0 h4 => ballStep_ne_id_of_lt_four h0 h4⟩,
    ⟨ball_card, hair_card⟩, fun f hf g hg => hairLift_unique f hf g hg,
    fun b => ⟨hairMk_ballStep b, hairMk_neg b⟩, ballReturn_iterate_hand, gate_iff_odd,
    selfLimit_eq, ⟨selfLimit_involutive, selfLimit_ne_id⟩, fun x hx => ?_⟩
  obtain ⟨h1, _, _, h4, h5⟩ := left_handed_potential_gate x hx
  exact ⟨h1, h4, h5⟩

end NRRF800

/-! ## Axiom audit -/

#print axioms NRRF800.nrrf800_answer
#print axioms NRRF800.left_handed_potential_gate
#print axioms NRRF800.four_acts_ball_blind
