import NRRF801BlackMirrorRelativeTranslationOneToOneClosureUnitaryCurvature

/-!
# NRRF802 — Unify closure

The instruction formalised here is the user's:

> unify closure

Up to now each module has built *its own* closure: the hair of the ball in NRRF800 (the quotient of
`Ball` by its translation), the one-to-one continuities of NRRF801, the closures of life by the
ball return and by the hair return, the relation readings of a configuration.  Each was defined by
hand, each came with its own universal property, and nothing said that they were the same
construction.

This module **unifies them**: it gives *one* closure operation, defined once for an arbitrary
return `step : X → X`, proves the universal property once, proves that the closure is the *unique*
such object up to a unique isomorphism, and then exhibits every previously constructed closure as
an instance of it.  Finally it unifies closure with itself: closing by two commuting returns at
once is the same as closing by one and then by the other, in either order.

## The construction

For `step : X → X`, `Closure step` is the quotient of `X` by the equivalence generated by
`b = step a`, with closure map `cl step`.  A *reading* of `X` is a map `f : X → Y`; it is *closed*
when `f ∘ step = f`.  Every closed reading factors uniquely through `cl step`.

## What is proved

### §1  One closure, once and for all
`cl_step`, `cl_iterate`, `cl_surjective`, `lift_cl`, `lift_unique`, `closure_isClosure`,
`closure_unique` (any two objects with the closure property are related by a *unique* isomorphism
commuting with the closure maps), `map`, `map_cl`, `map_id`, `map_comp`.

### §2  Every closure already built is this closure
`hair_isClosure` and `hair_eq_closure` (the hair of NRRF800 *is* the closure of the ball),
`hand_isClosure` and `closure_ballReturn_hand` (the closure of life by the actual return is exactly
its handedness), `phase_isClosure` and `closure_selfLimit_phase` (the closure of life by the self
limit is exactly the ball phase), together with the cardinalities `1`, `2`, `4`.

### §3  Closure unifies with itself
`Closure₂` (closing by two returns at once), `lift₂`, `closure₂_isClosure₂`, and the unification
theorems `unify_closure` (`Closure₂ f g ≃ Closure (pushforward of g)`, uniquely) and
`unify_closure_symm` (order does not matter).

### §4  Unified life
`closure₂_life_subsingleton` — closing life by *both* returns leaves exactly one point, the hair —
`unified_life_card_one`, `relations_unified` (every relation reading of every configuration lands
in that one point), and the tower `Hand`-then-inversion, `closure_hand_inv_subsingleton`.

### §5  `nrrf802_answer` collects the clauses; the axiom audit at the end is machine-checked.

Nothing here is asserted beyond the constructions: each word names a definition made here or in
NRRF800/NRRF801, and every claim is a claim about those definitions.
-/

namespace NRRF802

open NRRF800 NRRF801

universe u v

/-! ## §1  One closure, once and for all -/

section OneReturn

variable {X : Type u}

/-- The one-step return relation of a return `step`. -/
def ReturnRel (step : X → X) (a b : X) : Prop := b = step a

/-- The translational completion of a return: the equivalence it generates. -/
def returnSetoid (step : X → X) : Setoid X := Relation.EqvGen.setoid (ReturnRel step)

/-- **The closure of a return**: the quotient of `X` by the equivalence generated by one step. -/
def Closure (step : X → X) : Type u := Quotient (returnSetoid step)

/-- The closure map. -/
def cl (step : X → X) (x : X) : Closure step := Quotient.mk (returnSetoid step) x

theorem cl_surjective (step : X → X) : Function.Surjective (cl step) := Quotient.mk_surjective

/-- The closure reading is unmoved by the return. -/
@[simp] theorem cl_step (step : X → X) (x : X) : cl step (step x) = cl step x :=
  Quotient.sound (Relation.EqvGen.symm _ _ (Relation.EqvGen.rel _ _ rfl))

theorem cl_iterate (step : X → X) (n : ℕ) (x : X) : cl step (step^[n] x) = cl step x := by
  induction n with
  | zero => simp
  | succ n ih => rw [Function.iterate_succ_apply', cl_step, ih]

/-- A closed reading is constant along the generated equivalence. -/
theorem invariant_of_eqv {Y : Sort v} {step : X → X} (f : X → Y) (hf : ∀ x, f (step x) = f x)
    {a b : X} (h : Relation.EqvGen (ReturnRel step) a b) : f a = f b := by
  induction h with
  | rel a b hab => rw [show b = step a from hab, hf]
  | refl a => rfl
  | symm a b _ ih => exact ih.symm
  | trans a b c _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- **The universal property**: every closed reading factors through the closure. -/
def lift {Y : Sort v} (step : X → X) (f : X → Y) (hf : ∀ x, f (step x) = f x) :
    Closure step → Y :=
  Quotient.lift f (fun _ _ h => invariant_of_eqv f hf h)

@[simp] theorem lift_cl {Y : Sort v} (step : X → X) (f : X → Y) (hf : ∀ x, f (step x) = f x)
    (x : X) : lift step f hf (cl step x) = f x := rfl

/-- And the factorisation is unique. -/
theorem lift_unique {Y : Sort v} (step : X → X) (f : X → Y) (hf : ∀ x, f (step x) = f x)
    (g : Closure step → Y) (hg : ∀ x, g (cl step x) = f x) : g = lift step f hf := by
  funext c
  obtain ⟨x, rfl⟩ := cl_surjective step c
  rw [hg, lift_cl]

/-- Two maps out of a closure that agree on closure points are equal. -/
theorem closure_ext {Y : Sort v} {step : X → X} {g h : Closure step → Y}
    (hgh : ∀ x, g (cl step x) = h (cl step x)) : g = h := by
  funext c
  obtain ⟨x, rfl⟩ := cl_surjective step c
  exact hgh x

/-- **Being a closure**, stated without reference to any construction: `p : X → C` is closed and
every closed reading factors through it in exactly one way. -/
def IsClosure {C : Type u} (step : X → X) (p : X → C) : Prop :=
  (∀ x, p (step x) = p x) ∧
    ∀ (Y : Type u) (f : X → Y), (∀ x, f (step x) = f x) → ∃! g : C → Y, ∀ x, g (p x) = f x

/-- The closure is a closure. -/
theorem closure_isClosure (step : X → X) : IsClosure step (cl step) :=
  ⟨cl_step step, fun _ f hf => ⟨lift step f hf, lift_cl step f hf,
    fun g hg => lift_unique step f hf g hg⟩⟩

/-- **Closure is unique**: any two objects with the closure property of the same return are related
by exactly one isomorphism commuting with the closure maps.  This is what allows all the closures
built separately to be identified with one another. -/
theorem closure_unique {C D : Type u} {step : X → X} {p : X → C} {q : X → D}
    (hp : IsClosure step p) (hq : IsClosure step q) :
    ∃! e : C ≃ D, ∀ x, e (p x) = q x := by
  obtain ⟨hp1, hp2⟩ := hp
  obtain ⟨hq1, hq2⟩ := hq
  obtain ⟨g, hg, hguniq⟩ := hp2 D q hq1
  obtain ⟨h, hh, hhuniq⟩ := hq2 C p hp1
  have hgh : ∀ x, h (g (p x)) = p x := by intro x; rw [hg, hh]
  have hhg : ∀ x, g (h (q x)) = q x := by intro x; rw [hh, hg]
  have hidC : h ∘ g = id := by
    obtain ⟨_, _, huniq⟩ := hp2 C p hp1
    rw [huniq (h ∘ g) hgh, huniq id (fun _ => rfl)]
  have hidD : g ∘ h = id := by
    obtain ⟨_, _, huniq⟩ := hq2 D q hq1
    rw [huniq (g ∘ h) hhg, huniq id (fun _ => rfl)]
  refine ⟨⟨g, h, congrFun hidC, congrFun hidD⟩, hg, fun e he => ?_⟩
  have : (e : C → D) = g := hguniq _ he
  exact Equiv.coe_fn_injective this

/-- Functoriality: a map intertwining two returns descends to their closures. -/
def map {Y : Type u} {stepX : X → X} {stepY : Y → Y} (φ : X → Y)
    (hφ : ∀ x, φ (stepX x) = stepY (φ x)) : Closure stepX → Closure stepY :=
  lift stepX (fun x => cl stepY (φ x))
    (fun x => show cl stepY (φ (stepX x)) = cl stepY (φ x) by rw [hφ, cl_step])

@[simp] theorem map_cl {Y : Type u} {stepX : X → X} {stepY : Y → Y} (φ : X → Y)
    (hφ : ∀ x, φ (stepX x) = stepY (φ x)) (x : X) :
    map φ hφ (cl stepX x) = cl stepY (φ x) := rfl

theorem map_id (step : X → X) :
    map (stepX := step) (stepY := step) (id : X → X) (fun _ => rfl)
      = (id : Closure step → Closure step) :=
  closure_ext (fun _ => rfl)

theorem map_comp {Y Z : Type u} {stepX : X → X} {stepY : Y → Y} {stepZ : Z → Z}
    (φ : X → Y) (hφ : ∀ x, φ (stepX x) = stepY (φ x))
    (ψ : Y → Z) (hψ : ∀ y, ψ (stepY y) = stepZ (ψ y)) :
    map ψ hψ ∘ map φ hφ = map (ψ ∘ φ) (fun x => by simp [hφ, hψ]) :=
  closure_ext (fun _ => rfl)

end OneReturn

/-! ## §2  Every closure already built is this closure -/

/-- The hair of NRRF800 has the closure property of the ball's translation. -/
theorem hair_isClosure : IsClosure ballStep hairMk := by
  refine ⟨hairMk_ballStep, fun Y f hf => ⟨hairLift f hf, hairLift_mk f hf, ?_⟩⟩
  intro g hg
  exact hairLift_unique f hf g hg

/-- **The hair *is* the closure of the ball**: there is exactly one isomorphism between them
commuting with the two closure maps. -/
theorem hair_eq_closure : ∃! e : Hair ≃ Closure ballStep, ∀ b : Ball, e (hairMk b) = cl ballStep b :=
  closure_unique hair_isClosure (closure_isClosure ballStep)

/-- The closure of the ball is one point, like the hair. -/
instance : Subsingleton (Closure ballStep) := by
  constructor
  intro x y
  obtain ⟨a, rfl⟩ := cl_surjective ballStep x
  obtain ⟨b, rfl⟩ := cl_surjective ballStep y
  obtain ⟨n, -, hn⟩ := ballStep_transitive a b
  rw [← hn, cl_iterate]

/-- Life invariance: a reading of life closed under the actual return does not see the phase. -/
theorem closed_ballReturn_const (Y : Type) (f : Life → Y) (hf : ∀ x, f (ballReturn x) = f x)
    (h : Hand) (b : Ball) : f ⟨h, b⟩ = f ⟨h, 0⟩ := by
  have key : ∀ n : ℕ, ∀ x : Life, f (ballReturn^[n] x) = f x := by
    intro n
    induction n with
    | zero => intro x; simp
    | succ n ih => intro x; rw [Function.iterate_succ_apply', hf, ih]
  obtain ⟨n, -, hn⟩ := ballStep_transitive 0 b
  have hx : ballReturn^[n] (⟨h, 0⟩ : Life) = ⟨h, b⟩ := by
    rw [ballReturn_iterate]
    have : ((n : Ball)) = b := by
      rw [← hn, ballStep_iterate, zero_add]
    simp [this]
  rw [← hx, key]

/-- **The handedness of life has the closure property of the actual return.** -/
theorem hand_isClosure : IsClosure ballReturn Life.hand := by
  refine ⟨fun _ => rfl, fun Y f hf => ⟨fun h => f ⟨h, 0⟩, fun x => ?_, fun g hg => ?_⟩⟩
  · cases x with
    | mk h b => exact (closed_ballReturn_const Y f hf h b).symm
  · funext h
    have := hg ⟨h, 0⟩
    exact this

/-- **The closure of life by the actual return is exactly its handedness**, uniquely. -/
theorem closure_ballReturn_hand :
    ∃! e : Closure ballReturn ≃ Hand, ∀ x : Life, e (cl ballReturn x) = x.hand :=
  closure_unique (closure_isClosure ballReturn) hand_isClosure

/-- The self limit only inverts the hand, so a reading closed under it does not see the hand. -/
theorem closed_selfLimit_const (Y : Type) (f : Life → Y) (hf : ∀ x, f (selfLimit x) = f x)
    (h : Hand) (b : Ball) : f ⟨h, b⟩ = f ⟨Hand.left, b⟩ := by
  cases h with
  | left => rfl
  | right =>
      have := hf ⟨Hand.left, b⟩
      rw [selfLimit_eq] at this
      exact this

/-- **The ball phase of life has the closure property of the self limit.** -/
theorem phase_isClosure : IsClosure selfLimit Life.phase := by
  refine ⟨fun x => by rw [selfLimit_eq], fun Y f hf => ⟨fun b => f ⟨Hand.left, b⟩,
    fun x => ?_, fun g hg => ?_⟩⟩
  · cases x with
    | mk h b => exact (closed_selfLimit_const Y f hf h b).symm
  · funext b
    exact hg ⟨Hand.left, b⟩

/-- **The closure of life by the self limit is exactly its ball phase**, uniquely. -/
theorem closure_selfLimit_phase :
    ∃! e : Closure selfLimit ≃ Ball, ∀ x : Life, e (cl selfLimit x) = x.phase :=
  closure_unique (closure_isClosure selfLimit) phase_isClosure

/-- The three closures counted: the ball closes to one, life by the actual return closes to the two
hands, life by the self limit closes to the four phases. -/
theorem unified_cardinalities :
    Fintype.card Hair = 1 ∧ Fintype.card Hand = 2 ∧ Fintype.card Ball = 4 :=
  ⟨hair_card, Hand.card_hand, ball_card⟩

/-! ## §3  Closure unifies with itself -/

section TwoReturns

variable {X : Type u}

/-- The two-step return relation. -/
def Return₂Rel (f g : X → X) (a b : X) : Prop := b = f a ∨ b = g a

/-- The completion generated by two returns at once. -/
def return₂Setoid (f g : X → X) : Setoid X := Relation.EqvGen.setoid (Return₂Rel f g)

/-- **Closing by two returns at once.** -/
def Closure₂ (f g : X → X) : Type u := Quotient (return₂Setoid f g)

/-- The simultaneous closure map. -/
def cl₂ (f g : X → X) (x : X) : Closure₂ f g := Quotient.mk (return₂Setoid f g) x

theorem cl₂_surjective (f g : X → X) : Function.Surjective (cl₂ f g) := Quotient.mk_surjective

@[simp] theorem cl₂_left (f g : X → X) (x : X) : cl₂ f g (f x) = cl₂ f g x :=
  Quotient.sound (Relation.EqvGen.symm _ _ (Relation.EqvGen.rel _ _ (Or.inl rfl)))

@[simp] theorem cl₂_right (f g : X → X) (x : X) : cl₂ f g (g x) = cl₂ f g x :=
  Quotient.sound (Relation.EqvGen.symm _ _ (Relation.EqvGen.rel _ _ (Or.inr rfl)))

theorem invariant₂_of_eqv {Y : Sort v} {f g : X → X} (h : X → Y)
    (hf : ∀ x, h (f x) = h x) (hg : ∀ x, h (g x) = h x)
    {a b : X} (hab : Relation.EqvGen (Return₂Rel f g) a b) : h a = h b := by
  induction hab with
  | rel a b hab =>
      rcases hab with hab | hab
      · rw [show b = f a from hab, hf]
      · rw [show b = g a from hab, hg]
  | refl a => rfl
  | symm a b _ ih => exact ih.symm
  | trans a b c _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- The universal property of the simultaneous closure. -/
def lift₂ {Y : Sort v} (f g : X → X) (h : X → Y) (hf : ∀ x, h (f x) = h x)
    (hg : ∀ x, h (g x) = h x) : Closure₂ f g → Y :=
  Quotient.lift h (fun _ _ hab => invariant₂_of_eqv h hf hg hab)

@[simp] theorem lift₂_cl₂ {Y : Sort v} (f g : X → X) (h : X → Y) (hf : ∀ x, h (f x) = h x)
    (hg : ∀ x, h (g x) = h x) (x : X) : lift₂ f g h hf hg (cl₂ f g x) = h x := rfl

theorem lift₂_unique {Y : Sort v} (f g : X → X) (h : X → Y) (hf : ∀ x, h (f x) = h x)
    (hg : ∀ x, h (g x) = h x) (k : Closure₂ f g → Y) (hk : ∀ x, k (cl₂ f g x) = h x) :
    k = lift₂ f g h hf hg := by
  funext c
  obtain ⟨x, rfl⟩ := cl₂_surjective f g c
  rw [hk, lift₂_cl₂]

/-- The second return pushed forward to the closure by the first, when the two commute. -/
def push (f g : X → X) (hfg : ∀ x, f (g x) = g (f x)) : Closure f → Closure f :=
  lift f (fun x => cl f (g x))
    (fun x => show cl f (g (f x)) = cl f (g x) by rw [← hfg, cl_step])

@[simp] theorem push_cl (f g : X → X) (hfg : ∀ x, f (g x) = g (f x)) (x : X) :
    push f g hfg (cl f x) = cl f (g x) := rfl

/-- **Unification of closure**: closing by two commuting returns at once is the same as closing by
the first and then by the pushforward of the second — and the identification is unique. -/
theorem unify_closure (f g : X → X) (hfg : ∀ x, f (g x) = g (f x)) :
    ∃! e : Closure₂ f g ≃ Closure (push f g hfg),
      ∀ x : X, e (cl₂ f g x) = cl (push f g hfg) (cl f x) := by
  -- forward
  have hfwd₁ : ∀ x : X, cl (push f g hfg) (cl f (f x)) = cl (push f g hfg) (cl f x) := by
    intro x; rw [cl_step]
  have hfwd₂ : ∀ x : X, cl (push f g hfg) (cl f (g x)) = cl (push f g hfg) (cl f x) := by
    intro x
    rw [← push_cl f g hfg x, cl_step]
  let α : Closure₂ f g → Closure (push f g hfg) :=
    lift₂ f g (fun x => cl (push f g hfg) (cl f x)) hfwd₁ hfwd₂
  -- backward
  have hβ₀ : ∀ x : X, cl₂ f g (f x) = cl₂ f g x := cl₂_left f g
  let β₀ : Closure f → Closure₂ f g := lift f (cl₂ f g) hβ₀
  have hβ : ∀ c : Closure f, β₀ (push f g hfg c) = β₀ c := by
    intro c
    obtain ⟨x, rfl⟩ := cl_surjective f c
    show β₀ (cl f (g x)) = β₀ (cl f x)
    show cl₂ f g (g x) = cl₂ f g x
    exact cl₂_right f g x
  let β : Closure (push f g hfg) → Closure₂ f g := lift (push f g hfg) β₀ hβ
  have hαβ : ∀ c, α (β c) = c := by
    intro c
    obtain ⟨d, rfl⟩ := cl_surjective (push f g hfg) c
    obtain ⟨x, rfl⟩ := cl_surjective f d
    rfl
  have hβα : ∀ c, β (α c) = c := by
    intro c
    obtain ⟨x, rfl⟩ := cl₂_surjective f g c
    rfl
  refine ⟨⟨α, β, hβα, hαβ⟩, fun x => rfl, fun e he => ?_⟩
  have : (e : Closure₂ f g → Closure (push f g hfg)) = α := by
    funext c
    obtain ⟨x, rfl⟩ := cl₂_surjective f g c
    rw [he]
    rfl
  exact Equiv.coe_fn_injective this

/-- Closing by two returns does not depend on their order. -/
theorem unify_closure_symm (f g : X → X) :
    ∃! e : Closure₂ f g ≃ Closure₂ g f, ∀ x : X, e (cl₂ f g x) = cl₂ g f x := by
  let α : Closure₂ f g → Closure₂ g f := lift₂ f g (cl₂ g f) (cl₂_right g f) (cl₂_left g f)
  let β : Closure₂ g f → Closure₂ f g := lift₂ g f (cl₂ f g) (cl₂_right f g) (cl₂_left f g)
  have hαβ : ∀ c, α (β c) = c := by
    intro c
    obtain ⟨x, rfl⟩ := cl₂_surjective g f c
    rfl
  have hβα : ∀ c, β (α c) = c := by
    intro c
    obtain ⟨x, rfl⟩ := cl₂_surjective f g c
    rfl
  refine ⟨⟨α, β, hβα, hαβ⟩, fun x => rfl, fun e he => ?_⟩
  have : (e : Closure₂ f g → Closure₂ g f) = α := by
    funext c
    obtain ⟨x, rfl⟩ := cl₂_surjective f g c
    rw [he]
    rfl
  exact Equiv.coe_fn_injective this

end TwoReturns

/-! ## §4  Unified life -/

/-- The two returns of life commute. -/
theorem life_returns_commute (x : Life) : ballReturn (hairReturn x) = hairReturn (ballReturn x) :=
  congrFun ball_hair_commute x

/-- The simultaneous closure of life is unmoved by the self limit. -/
theorem cl₂_selfLimit (x : Life) :
    cl₂ ballReturn hairReturn (selfLimit x) = cl₂ ballReturn hairReturn x := by
  rw [selfLimit]
  rw [cl₂_right, cl₂_left]

/-- **Closing life by both returns leaves exactly one point.** -/
instance closure₂_life_subsingleton : Subsingleton (Closure₂ ballReturn hairReturn) := by
  constructor
  intro c d
  obtain ⟨x, rfl⟩ := cl₂_surjective ballReturn hairReturn c
  obtain ⟨y, rfl⟩ := cl₂_surjective ballReturn hairReturn d
  have key : ∀ z : Life, cl₂ ballReturn hairReturn z
      = cl₂ ballReturn hairReturn (⟨Hand.left, 0⟩ : Life) := by
    intro z
    have hphase : ∀ h : Hand, ∀ b : Ball, cl₂ ballReturn hairReturn (⟨h, b⟩ : Life)
        = cl₂ ballReturn hairReturn (⟨h, 0⟩ : Life) := by
      intro h b
      obtain ⟨n, -, hn⟩ := ballStep_transitive 0 b
      have hb : ((n : Ball)) = b := by rw [← hn, ballStep_iterate, zero_add]
      have hx : ballReturn^[n] (⟨h, 0⟩ : Life) = ⟨h, b⟩ := by
        rw [ballReturn_iterate, hb]
        simp
      rw [← hx]
      clear hx hn hb
      induction n with
      | zero => simp
      | succ n ih =>
          rw [Function.iterate_succ_apply', cl₂_left]
          exact ih
    have hhand : ∀ b : Ball, cl₂ ballReturn hairReturn (⟨Hand.right, b⟩ : Life)
        = cl₂ ballReturn hairReturn (⟨Hand.left, b⟩ : Life) := by
      intro b
      have := cl₂_selfLimit (⟨Hand.left, b⟩ : Life)
      rw [selfLimit_eq] at this
      exact this
    cases z with
    | mk h b =>
        cases h with
        | left => exact hphase Hand.left b
        | right => rw [hphase Hand.right b, hhand 0]
  rw [key x, key y]

instance : Inhabited (Closure₂ ballReturn hairReturn) := ⟨cl₂ _ _ ⟨Hand.left, 0⟩⟩

instance : Unique (Closure₂ ballReturn hairReturn) := Unique.mk' _

noncomputable instance : Fintype (Closure₂ ballReturn hairReturn) :=
  Fintype.ofSubsingleton (cl₂ _ _ ⟨Hand.left, 0⟩)

/-- **The unified closure of life is one point** — the hair, again. -/
theorem unified_life_card_one : Fintype.card (Closure₂ ballReturn hairReturn) = 1 :=
  Fintype.card_eq_one_iff.2 ⟨cl₂ _ _ ⟨Hand.left, 0⟩, fun _ => Subsingleton.elim _ _⟩

/-- Unified life is the tower as well: closing by the actual return, then by the pushed potential
return, gives the same one point. -/
theorem unified_life_tower :
    ∃! e : Closure₂ ballReturn hairReturn ≃
        Closure (push ballReturn hairReturn life_returns_commute),
      ∀ x : Life, e (cl₂ ballReturn hairReturn x)
        = cl (push ballReturn hairReturn life_returns_commute) (cl ballReturn x) :=
  unify_closure ballReturn hairReturn life_returns_commute

/-- Every relation reading of every configuration lands in that single unified point. -/
theorem relations_unified {V : Type*} (s t : Config V) (u v u' v' : V) :
    cl₂ ballReturn hairReturn (relLife s u v) = cl₂ ballReturn hairReturn (relLife t u' v') :=
  Subsingleton.elim _ _

/-- The tower read at the level of hands: the closure of the two hands by the inversion is one
point too, so the unification agrees with NRRF800's hair count. -/
theorem closure_hand_inv_subsingleton (c d : Closure Hand.inv) : c = d := by
  obtain ⟨h, rfl⟩ := cl_surjective Hand.inv c
  obtain ⟨h', rfl⟩ := cl_surjective Hand.inv d
  cases h <;> cases h' <;>
    first
      | rfl
      | (exact (cl_step Hand.inv Hand.left).symm)
      | (exact cl_step Hand.inv Hand.left)

/-! ## §5  The answer -/

/-- **NRRF802 in one statement.**

1. There is one closure operation for an arbitrary return, with one universal property: every
   reading unmoved by the return factors through it in exactly one way.
2. It is unique: any two objects with the closure property are related by exactly one isomorphism
   commuting with the closure maps, so all closures built separately are the same closure.
3. It is functorial: maps intertwining returns descend, identities and composites are preserved.
4. The hair of the ball, the handedness of life, and the ball phase of life are its instances —
   the closures of `ballStep`, `ballReturn`, `selfLimit` respectively.
5. Closure unifies with itself: closing by two commuting returns at once is the closure of the
   closure, and the order of the two returns does not matter.
6. Closing life by both of its returns leaves exactly one point. -/
theorem nrrf802_answer :
    (∀ (X Y : Type) (step : X → X) (f : X → Y), (∀ x, f (step x) = f x) →
        ∃! g : Closure step → Y, ∀ x, g (cl step x) = f x) ∧
    (∀ (X C D : Type) (step : X → X) (p : X → C) (q : X → D),
        IsClosure step p → IsClosure step q → ∃! e : C ≃ D, ∀ x, e (p x) = q x) ∧
    (IsClosure ballStep hairMk ∧ IsClosure ballReturn Life.hand ∧
      IsClosure selfLimit Life.phase) ∧
    (Fintype.card Hair = 1 ∧ Fintype.card Hand = 2 ∧ Fintype.card Ball = 4) ∧
    (∀ (X : Type) (f g : X → X) (hfg : ∀ x, f (g x) = g (f x)),
        ∃! e : Closure₂ f g ≃ Closure (push f g hfg),
          ∀ x : X, e (cl₂ f g x) = cl (push f g hfg) (cl f x)) ∧
    (∀ (X : Type) (f g : X → X), ∃! e : Closure₂ f g ≃ Closure₂ g f,
        ∀ x : X, e (cl₂ f g x) = cl₂ g f x) ∧
    Fintype.card (Closure₂ ballReturn hairReturn) = 1 := by
  refine ⟨fun X Y step f hf => ⟨lift step f hf, lift_cl step f hf,
      fun g hg => lift_unique step f hf g hg⟩,
    fun X C D step p q hp hq => closure_unique hp hq,
    ⟨hair_isClosure, hand_isClosure, phase_isClosure⟩,
    unified_cardinalities, fun X f g hfg => unify_closure f g hfg,
    fun X f g => unify_closure_symm f g, unified_life_card_one⟩

end NRRF802

/-! ## Axiom audit -/

#print axioms NRRF802.nrrf802_answer
#print axioms NRRF802.closure_unique
#print axioms NRRF802.unify_closure
#print axioms NRRF802.unified_life_card_one
