import NRRFTradingExecutorReactorTranslationalTruthReunification

/-!
# Trading 0–∞ fold/unfold repetition gate

This module integrates the reported NRRF806 reading into the active trading bridge without
claiming an import of a source file that is not present in this checkout.  It uses the already
verified return closure and executer/reactor being:

* the infinity pole is the least internal equality form generated by the beat;
* the zero pole is the greatest equality form, identifying every presentation;
* folding is the quotient map and unfolding is the forward orbit;
* repetition can be read only after a translation step has been authored.

The last clause is load-bearing for trading.  Public books can populate reactor presentations,
but they do not by themselves author the system's action or potential step.  Therefore no
price-pattern recurrence is manufactured as a signal.
-/

namespace NRRFTradingZeroInf

open NRRF800 NRRF802 NRRFTradingExecutorReactor

universe u

section Generic

variable {X : Type u}

/-- The infinity pole: the line generated by the supplied translation. -/
def infPole (step : X → X) : Setoid X := returnSetoid step

/-- The zero pole: every presentation is one point. -/
def zeroPole : Setoid X := ⊤

/-- Internal equality is defined only relative to a translation. -/
def InternalForm (step : X → X) (form : Setoid X) : Prop :=
  ∀ x, form.r x (step x)

/-- Every internal form contains the infinity pole generated by the translation. -/
theorem closure_le_internal {step : X → X} {form : Setoid X}
    (internal : InternalForm step form) : infPole step ≤ form := by
  intro left right related
  induction related with
  | rel left right relation =>
      rw [show right = step left from relation]
      exact internal left
  | refl point => exact form.refl point
  | symm left right _ ih => exact form.symm ih
  | trans left middle right _ _ ihLeft ihRight => exact form.trans ihLeft ihRight

/-- Internal forms are exactly the interval between the infinity and zero poles. -/
theorem internal_iff_between (step : X → X) (form : Setoid X) :
    InternalForm step form ↔ infPole step ≤ form ∧ form ≤ zeroPole := by
  constructor
  · intro internal
    exact ⟨closure_le_internal internal, fun _ _ _ => trivial⟩
  · intro between x
    exact between.1 (Relation.EqvGen.rel x (step x) rfl)

/-- The infinity pole is the least form internal for its translation. -/
theorem infPole_isLeast (step : X → X) :
    InternalForm step (infPole step) ∧
      ∀ form, InternalForm step form → infPole step ≤ form := by
  constructor
  · intro x
    exact Relation.EqvGen.rel x (step x) rfl
  · intro form internal
    exact closure_le_internal internal

/-- The zero pole is the greatest internal form. -/
theorem zeroPole_isGreatest (step : X → X) :
    InternalForm step (zeroPole : Setoid X) ∧
      ∀ form : Setoid X, form ≤ zeroPole := by
  exact ⟨fun _ => trivial, fun _ _ _ _ => trivial⟩

/-- The zero pole is itself the closure of a true translation: the constant return to a supplied
point. -/
theorem zeroPole_eq_returnSetoid_const (anchor : X) :
    (zeroPole : Setoid X) = returnSetoid (fun _ => anchor) := by
  apply Setoid.ext
  intro left right
  constructor
  · intro _
    exact Relation.EqvGen.trans left anchor right
      (Relation.EqvGen.rel left anchor rfl)
      (Relation.EqvGen.symm right anchor (Relation.EqvGen.rel right anchor rfl))
  · intro _
    trivial

/-- The forward unfolding of a point. -/
def Unfold (step : X → X) (x : X) : Set X :=
  {y | ∃ n : ℕ, step^[n] x = y}

/-- The fold of the translation. -/
def Fold (step : X → X) (x : X) : Closure step := cl step x

/-- Unfolding never leaves the fold. -/
theorem unfold_stays_in_fold (step : X → X) (x y : X) (hy : y ∈ Unfold step x) :
    Fold step y = Fold step x := by
  rcases hy with ⟨n, rfl⟩
  exact cl_iterate step n x

/-- A point repeats only relative to a supplied translation. -/
def Repeats (step : X → X) (x : X) : Prop :=
  ∃ n : ℕ, 0 < n ∧ step^[n] x = x

/-- Repetition is return of the unfolded path to its own origin. -/
theorem repeats_iff_origin_in_return_unfold (step : X → X) (x : X) :
    Repeats step x ↔ x ∈ Unfold step (step x) := by
  constructor
  · rintro ⟨n, positive, repeated⟩
    obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt positive)
    exact ⟨m, by simpa [Function.iterate_succ_apply] using repeated⟩
  · rintro ⟨n, returned⟩
    exact ⟨n + 1, Nat.succ_pos n, by
      simpa [Function.iterate_succ_apply] using returned⟩

end Generic

/-! ## Trading specialization -/

/-- The local reactor line is the infinity pole of the life beat. -/
def tradingInfPole : Setoid Life := infPole lifeBeing.beat

/-- The global executer point is the zero pole. -/
def tradingZeroPole : Setoid Life := zeroPole

theorem trading_infPole_iff_reactor (left right : Life) :
    tradingInfPole.r left right ↔ react left = react right :=
  beatClosureRel_iff_react_eq left right

theorem trading_zeroPole_all (left right : Life) : tradingZeroPole.r left right := trivial

/-- The two trading poles are derived and bound every equality form internal for the beat. -/
theorem trading_internal_iff_between (form : Setoid Life) :
    InternalForm lifeBeing.beat form ↔ tradingInfPole ≤ form ∧ form ≤ tradingZeroPole :=
  internal_iff_between lifeBeing.beat form

/-- The poles remain distinct for the life beat: the reactor retains four phases while the
executer identifies them. -/
theorem trading_zero_ne_inf : tradingZeroPole ≠ tradingInfPole := by
  intro same
  have related : tradingInfPole.r (⟨Hand.left, 0⟩ : Life) ⟨Hand.left, 1⟩ := by
    rw [← same]
    trivial
  have phases := (trading_infPole_iff_reactor _ _).1 related
  have distinct : (0 : Ball) ≠ 1 := by decide
  exact distinct phases

/-- The being's beat repeats on its formal carrier in two turns. -/
theorem lifeBeat_repeats (life : Life) : Repeats lifeBeing.beat life := by
  refine ⟨2, by decide, ?_⟩
  rw [lifeBeing_beat]
  simpa only [Function.iterate_succ_apply', Function.iterate_zero_apply, Function.comp_apply]
    using selfLimit_involutive life

/-- Repetition is a partial reading of the market interface: without an authored turn there is no
translation whose orbit could be tested. -/
def repetitionReading (interface : TradingInterface) : Option Prop :=
  interface.authoredTurn.map fun turn => Repeats (authoredStep turn) interface.reactorState

theorem no_authored_turn_no_repetition_reading (life : Life) :
    repetitionReading (TradingInterface.mk life none) = none := rfl

theorem action_authored_repeats (life : Life) :
    Repeats (authoredStep .action) life := by
  refine ⟨4, by decide, ?_⟩
  exact congrFun ballReturn_period life

theorem potential_authored_repeats (life : Life) :
    Repeats (authoredStep .potential) life := by
  refine ⟨4, by decide, ?_⟩
  exact congrFun hairReturn_period life

/-- Complete trading reading: the poles are intrinsic, while repetition and signal identification
remain absent until interaction supplies the translation. -/
theorem zeroInf_trading_answer (life : Life) :
    (∀ form : Setoid Life,
      InternalForm lifeBeing.beat form ↔ tradingInfPole ≤ form ∧ form ≤ tradingZeroPole) ∧
    (∀ other, tradingInfPole.r life other ↔ react life = react other) ∧
    (∀ other, tradingZeroPole.r life other) ∧
    Repeats lifeBeing.beat life ∧
    (TradingInterface.mk life none).identifiedForm = none ∧
    repetitionReading (TradingInterface.mk life none) = none := by
  exact ⟨trading_internal_iff_between, trading_infPole_iff_reactor life,
    trading_zeroPole_all life, lifeBeat_repeats life,
    no_authored_turn_no_identified_form life, no_authored_turn_no_repetition_reading life⟩

#print axioms internal_iff_between
#print axioms zeroPole_eq_returnSetoid_const
#print axioms trading_zero_ne_inf
#print axioms zeroInf_trading_answer

end NRRFTradingZeroInf
